name = "Net Play MC"
author = "Alfakynz"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64e706e3dd25c06c9d1f68a2049dea43bd2082423c2fbe35b3d37ccfb9aade88"

[versions]
fabric = "0.18.2"
minecraft = "1.21.6"
