hash-format = "sha256"

[[files]]
file = "config/betterf3.json"
hash = "0028abb010568e5d31c2d12390a18a471a495591a24bf408abea3c151e8d234e"

[[files]]
file = "config/euphoria_patcher.properties"
hash = "66793f6eb032dba20841b7b015cf96550baec9686ee9cf758edc2e41b193ec25"

[[files]]
file = "config/inventoryprofilesnext/integrationHints/exampleIntegrationHints.json"
hash = "ca413dea02cce69c69dccdc525fb0ec013236876eff2d142772c68db3d772d3a"

[[files]]
file = "config/inventoryprofilesnext/inventoryprofiles.json"
hash = "cc6948c287851fdb08146d86250841e4d6ee9c802ebba1f8df13aa3445528be0"

[[files]]
file = "config/jade/hide-blocks.json"
hash = "309df4ae96864c19eae41b646d58497c85a73b1fc3c584e772ef4d5822794baa"

[[files]]
file = "config/jade/hide-entities.json"
hash = "3741bb54a4535fb5a00fb0ee1f4386f3dd17834aebdf9e89c21fcd3307109709"

[[files]]
file = "config/jade/jade.json"
hash = "8a57b8690ae69bac1e3c575a1a841a0c017f5ab3baadb6ba78f71a4bf0541ce0"

[[files]]
file = "config/jade/plugins.json"
hash = "8daf20878a02aab8611856f409ea0b33f721ef1d5be4bad4053d446e9634ba28"

[[files]]
file = "config/jade/sort-order.json"
hash = "d3f3be9b97417e8f177e1500b1d1f606562749b2eca47387eff162dc1b924e24"

[[files]]
file = "config/jade/usernamecache.json"
hash = "b22ed10ad081a907fe3e34e91cd8664ae80391ec8053fb9bede77fd2c44d7dd9"

[[files]]
file = "config/roughlyenoughitems/config.json5"
hash = "e20428580f54cb128b11bb54b38b4c9957473f5494628bcf42c7c358276f9759"

[[files]]
file = "config/rrls.toml"
hash = "e640a0284af42c946e5495440466beae329f32f9b7aa068a9d1d51559b9624f8"

[[files]]
file = "config/shouldersurfing-client.toml"
hash = "880d1725e8bc4b9a4fb2753a5d698fa380d822afb007cd92d618e7254ea3ff33"

[[files]]
file = "config/skinshuffle/config.json"
hash = "662c8542ea661fc5321a22e99df6dafd0d6055ed0416a3fc767df130a9953a52"

[[files]]
file = "icon.png"
hash = "c36c0efbe5be0b9cf0fdfe54dbe17bea53295ac2a372d1203aa0f5c9c68d2bc7"

[[files]]
file = "journeymap/config/6.0/journeymap.core.config"
hash = "f186361722ed93165d61b42169ee0495310f7032b32a77f0f09c34f1c8dff6e3"

[[files]]
file = "journeymap/config/6.0/journeymap.fullmap.config"
hash = "b767cc9b4c8f8aadd2f07e03af345b51a44077d5a5c9d6ff491d57f0bb5d2e32"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap.config"
hash = "8cda76eb64346eb0b4c4fd567aa32b8a2c752a6600170db33729568ef0f7ad70"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap2.config"
hash = "26fd46b816044dbbc8fbd5fca1514b77598db69d3c239195edf0d7a40f969685"

[[files]]
file = "journeymap/config/6.0/journeymap.rendering.config"
hash = "adb365c27dcbf3a24b697cdb63f96bc6b09a179a2bea94397d146bdb890ac967"

[[files]]
file = "journeymap/config/6.0/journeymap.topo.config"
hash = "429c48cf38f5acb051b98ac7577e95fcf48b297d01cd83fd36e07c24c8416cad"

[[files]]
file = "journeymap/config/6.0/journeymap.waypoint.config"
hash = "a6e25c86ca2b8aa32a85829d7c39a31ccae7d749b240a55ea2000cb8cbcc490c"

[[files]]
file = "journeymap/config/6.0/journeymap.webmap.config"
hash = "6f472441a8c7377731ff5f9ad43f46951595c8a4969d1ba4b1055aa185a38c23"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "23fb3895299b959d4dc8852cd235c67a723cc43da4d7f8136d73c7b3256d28fa"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1bf302009fc75c3519ea095753fe926af91b0a2dce732d1775fa1920aca8e56a"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "57c4935e001e8d1688d226b0d54027395913aa861302d7c3307bf04ea1848392"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "72341600c6dc91dc11e1293a4fb87b594d9786c86b8e93b16680ea0973d92449"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "5e2ca4f2d068e0236d7a995baabe4293b8fd1291d354d55c8337710329ccf4fe"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "a8321c6d297c9a266a82600942a2b329f374abb9f3fdd0810499a2f26a082b2d"
metafile = true

[[files]]
file = "mods/better-selection.pw.toml"
hash = "ddb17abac95266f5845b2cc14acec1292e27f17da94acf423569b55f75ec8a7f"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "5a05b8c01319f72373ae725ce8ae531993ed3e44a55e19ae80a12224f5d27123"
metafile = true

[[files]]
file = "mods/betterstats.pw.toml"
hash = "c6b8af91f201644f75711d5605b15203c9bbfc986df00e1b17176628c1914a4d"
metafile = true

[[files]]
file = "mods/bridging-mod.pw.toml"
hash = "898a383ad33bb172ac111b2a038d383e02eae4c54fe25cbf3f0f11cc17eab5e5"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "c1ee4714f23846f70b6a150d965990264eda55a9e213c1baa8472a7be05a12f9"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "de8e021e0beacab839ca3bd4dfdb30fa5f3cfd1e71be722ccf56373908b41a7f"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "ebb83ff56fd213d1e0efb57d59a89a6c864c7be63436e028fec02878b300e426"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "f30a1a38054ad25b5105c463962c5b5fc53a070e0e860d4d7951208b333e3f7a"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a826fbce1a20169613e387719b40a05e95a0ca8ede805b82fa686533a0550713"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "b90a39972e2b4468f6b02127a1e370cd10a976fdae0d82527fa048e23e45b093"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "aba6398c78f281146fa114aafec5817ece9378d91e4bdd85213c95d50a7d4492"
metafile = true

[[files]]
file = "mods/detail-armor-bar-reconstructed.pw.toml"
hash = "35655c9869f280f3bb2d81ecf06041b7b2cd6a038655fbfb5a9bb776f015795f"
metafile = true

[[files]]
file = "mods/dynamic-crosshair.pw.toml"
hash = "49975a49af51ec632ca329870f383f94034e44913cd7a9b64b701efe97e5d068"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "b8f6040c1859b1df8d144d71133809605005a35f10a7c54126fe19d135c772cd"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "3303ffc99bfefa5591660f2654766dac92666590c27a192cc88a5808cd120763"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "f4919e8852bd9d4a890eb19ff87070b80b575453a189ac41510775f100fe8d90"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "1216b6a5ad4ffceaf82ab6bab330499d346cf907db8dea6054537744f88c5b59"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "6ea66b4a4c5a4db9cda995ec4273d20f49329b1c243e48e18420513abcd01b26"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "212a90f8ab7004e831d3a956c27f8fd522b894569e7e4d36268d894f00cf5583"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "189134fe48404ea4f716f6ee705d5af668a493264c1af07b02ce18113b346de9"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "94f000249d21c4fc3b7744f9579bb6ac0d48e6bf4860fad16f23c997950a47f3"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "da4720149fabb3d338ff2d4d6eb59cb248e5210f8c515e2aa069731ff058c5d3"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "47a38ead307c2d86ac06e12f70847dc0194da9014608d4ac7b4133ae6a5abdda"
metafile = true

[[files]]
file = "mods/first-person-model.pw.toml"
hash = "ed0e07891a0c790f2b0bddf4363f2012954659958b6002c170a3bc1c5a53023e"
metafile = true

[[files]]
file = "mods/forge-config-api-port-fabric.pw.toml"
hash = "3f793cb78a7b12af9f43914e55fd158789db5f69f69205a897e11cdd6569c367"
metafile = true

[[files]]
file = "mods/free-inventory.pw.toml"
hash = "d6588fade687ae5254313807598cd7732f1917e71dc202e387d11a077ab09d6c"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "778bf63381f45639875bea198ebdcc559923f87365b2976d64f205d75c5931fc"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "c3b8abec750268c238b08e41f81b69da524064284f17f63ef055a3bcf3bac4f9"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "2857a8dc942967be661710354790ccbd996f2c32d4b2c9ea7a5554ace3d98b97"
metafile = true

[[files]]
file = "mods/invmovecompats.pw.toml"
hash = "e08e7d05219d12b4de7083b2f7ec5424cf75d653e940633fff44d8def47db7e5"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "427b4d017b83401708e96e36f11f11c7474365011b108b255f69e000ecc6422c"
metafile = true

[[files]]
file = "mods/itemphysic.pw.toml"
hash = "cf70760763ba76bf324d12b1f03145f53929343e387a325af407f2fb37ed822c"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "179047f50e0b2eb0fc669fded7c6a480441d7e8a0961453b2e21274c4d8f2e1c"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "c75fefbf0abf36da4f2de6e7da8d6988e9bc2301d0ada850755c86c5f315fe8e"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "9ff43b83964cac8079c9228ba9864222472e7ba3ff0a664144b3a35352012522"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "bcfd26bc56aa72b4edd5cd6a025137e51dc6cb4a7866a7665511009404d13bb9"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "a3e8ab5b65ff403b1e578f50465a67743ff2d6943bd47458be482e44f5642754"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "571d53be7a248e0961bf769252695b996e14c5daa70a298c52877844ebc8b20f"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "eb23a8bbd09621c14ce02a935573a6903125f9d8d92806152ebca8c16a5a9fd0"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "9a5062df61e09bf79936d0987a252aac26506b51d7c02107e4ca386c0c5a196c"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "0231d69e8d44350d5bb490b6c8d08f9b074397423cf68b61448f8528fdd19c42"
metafile = true

[[files]]
file = "mods/no-more-popups.pw.toml"
hash = "53633508694b314c003866564cc4b8099982ec840d18d21b761459513a253f8c"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "56605167b88bb170da3643a32a810d51ce0a9c0c82e7b8f1dcbca4dfa909d8a6"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "2892ef637c93b1255b6ee01eab9b27afa27fe42664094130ba0d560c8a320713"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "4478b3a42925deadb386d54a10a37207d76dc6d6b5bb90e764e5a40f94bdb80f"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "bd5a56412de73022eba1895b1064ddd19362f188d8d0fd977ed208dfc18c041e"
metafile = true

[[files]]
file = "mods/roughly-enough-items.pw.toml"
hash = "24ec005442cecbe94a971c838eee430eef40b0bb15d4678a579436a5aaf9d865"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "2432429f4a67513150f12b44e5c6f67d9c4eb167e8c3b12ac5f3b136749bf293"
metafile = true

[[files]]
file = "mods/shoulder-surfing-reloaded.pw.toml"
hash = "cc6f92e78af23c38cfd07ace4459c965bc9e020939a9f6ef737dfa17bee8d752"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "4bd4b4f144397a7ab90fa7b6c86d88ca6b55369ce24e82c98b69075c2521a7b2"
metafile = true

[[files]]
file = "mods/skin-layers-3d.pw.toml"
hash = "d5b4d4d4e1191f459196b3c18d9ff7d71bc8e49a24f5df782ff2c3e800484f94"
metafile = true

[[files]]
file = "mods/skinshuffle.pw.toml"
hash = "d64c04590f64d9d60c735556b2b88d947907514c4b1e55bdf72ac02239e9ca9e"
metafile = true

[[files]]
file = "mods/smooth-scroll.pw.toml"
hash = "614ab32c2bfdecd7ea3ebd0f65afb06e2dd1c1e1009469ec3ad541a5068ec147"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "5269b2f8b0eb0ca98052d13cad6fe6417d13d064162fb1d95323626398c56587"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "cdf62992a654bf76495b999867271cd63f777e7af821ad2ca3f4099ccf58cd9d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "24aa12652da15e0e2d788a4cc2144ef908d6b4a792b644becd64ca3e1bfe4fe7"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "d15030e4fa60cde40cebe6764475fd4a7383b3a37e3a1e2a96461f7730ff1b6e"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "910452addf61893bacdcd8eb7659236a2fc4f57452a61ec3ecfe497abc74b4b2"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "27dc7fefde6ef779c53c2c517ab6992373c2266ca812661d65facf72e6bb31d0"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
hash = "c5fdf842ac50d5992853c9c6f073d876d358913b161498eb2f52b1de58d2a390"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "f49c6cc93bf7527571e4b756f5f5632a198de48a3930482a7d9c231360fa6348"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "74c920cae58e2e159507b6d1c2e7485d4e628368e33593c1ddaef03b9c669ff9"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "95351a8e1eacbfe181024d281f5b87c93dd545319a21b5dd30ba45e4c8a94678"
metafile = true

[[files]]
file = "options.txt"
hash = "bc307212710702f562d4887c8f921e3c3917045041c6cc9383b540355ebc55c3"

[[files]]
file = "resourcepacks/better-ipn-buttons.pw.toml"
hash = "344cfb1bf3259c3534dc0b0737aef164f0f3c97ddf75f15fd564fbd93c427c0d"
metafile = true

[[files]]
file = "resourcepacks/connected-paths.pw.toml"
hash = "3d81c2d42dadb03acc48f5e50763cbc52daf1557ad3104ba397c90e3a55814b4"
metafile = true

[[files]]
file = "resourcepacks/eating-animation-resource-pack.pw.toml"
hash = "5da2d254ce79909463b3a1e655fd1ecab89449ec6c6f7f5e014b164263a9cd35"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "2d8aab62e51d84e33920e15cdd34fd164d971b01aede0c3d17abcd08117d33a9"
metafile = true

[[files]]
file = "resourcepacks/fast-better-grass.pw.toml"
hash = "5310da73a0fb83b049f5e5a3fdd82c73873da024d0ce663a2365c209c002fd0a"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "15f5872ee75d21be2e6cbd25669e423a2a764312562e5cdfdc4e34af160dc6d3"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "9532816a020467d30459bbd3f42806916ffd33f79b1fdbae5e7b25a3af71a372"
metafile = true

[[files]]
file = "resourcepacks/minecraft-3d-default.pw.toml"
hash = "b7e15b60c2dc789a55abec62321393ddcb349c4e6f14646b24a0f07fc7bb6df5"
metafile = true

[[files]]
file = "resourcepacks/recolourful-containers-gui-hud-dark.pw.toml"
hash = "91d9ebebc72f713caf3c181839d2966190e3018fdcf87fd02ffa94e1244cf6df"
metafile = true

[[files]]
file = "resourcepacks/torches-reimagined.pw.toml"
hash = "24ac06885ef01025f8abe7d57ae0452bb18ca9eba084092ce2fc444f6272da58"
metafile = true

[[files]]
file = "resourcepacks/translations-for-sodium.pw.toml"
hash = "7fb83199c50d224fcf15e229e9168bd5412ca353927452e2a52bc08eb5443a24"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "006170836f3180d229a6b95e1b33c060d7afcd0755273669faf78e86f50579ed"
metafile = true
