hash-format = "sha256"

[[files]]
file = "config/betterf3.json"
hash = "0028abb010568e5d31c2d12390a18a471a495591a24bf408abea3c151e8d234e"

[[files]]
file = "config/detailarmorbar.json"
hash = "a5c688952ee55d6ac48c632baa5667d8adc20758ab2fd6c913c1b411bb4cad71"

[[files]]
file = "config/euphoria_patcher.properties"
hash = "66793f6eb032dba20841b7b015cf96550baec9686ee9cf758edc2e41b193ec25"

[[files]]
file = "config/inventoryprofilesnext/inventoryprofiles.json"
hash = "3b2f0b16fe70aa6a7720622bf7dcb99e59e412c37169763b3af0c8b310b74d5e"

[[files]]
file = "config/iris.properties"
hash = "4eb525ec220ff749911e5d1f8f6eab09ec9d78875dd4baf6d63e6a50ba069ac0"

[[files]]
file = "config/jade/jade.json"
hash = "93e098f8882bbfe9eaba05694016fff55a911114d1cea2a046915e6f4253d64b"

[[files]]
file = "config/jade/plugins.json"
hash = "8daf20878a02aab8611856f409ea0b33f721ef1d5be4bad4053d446e9634ba28"

[[files]]
file = "config/no-more-popups.json"
hash = "31e5140ee7bb35c73c8ae74eb785eca3c81caf235d467fd4a38e75e86e0a6aa7"

[[files]]
file = "config/roughlyenoughitems/config.json5"
hash = "e20428580f54cb128b11bb54b38b4c9957473f5494628bcf42c7c358276f9759"

[[files]]
file = "config/rrls.toml"
hash = "e640a0284af42c946e5495440466beae329f32f9b7aa068a9d1d51559b9624f8"

[[files]]
file = "config/shouldersurfing-client.toml"
hash = "880d1725e8bc4b9a4fb2753a5d698fa380d822afb007cd92d618e7254ea3ff33"

[[files]]
file = "config/skinshuffle/config.json"
hash = "662c8542ea661fc5321a22e99df6dafd0d6055ed0416a3fc767df130a9953a52"

[[files]]
file = "config/voicechat/voicechat-client.properties"
hash = "565252c49707cbd0503824432c6cde64739eaa56130c1d3b8096c6754ca25853"

[[files]]
file = "icon.png"
hash = "c36c0efbe5be0b9cf0fdfe54dbe17bea53295ac2a372d1203aa0f5c9c68d2bc7"

[[files]]
file = "journeymap/config/6.0/journeymap.core.config"
hash = "f186361722ed93165d61b42169ee0495310f7032b32a77f0f09c34f1c8dff6e3"

[[files]]
file = "journeymap/config/6.0/journeymap.fullmap.config"
hash = "b767cc9b4c8f8aadd2f07e03af345b51a44077d5a5c9d6ff491d57f0bb5d2e32"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap.config"
hash = "8cda76eb64346eb0b4c4fd567aa32b8a2c752a6600170db33729568ef0f7ad70"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap2.config"
hash = "26fd46b816044dbbc8fbd5fca1514b77598db69d3c239195edf0d7a40f969685"

[[files]]
file = "journeymap/config/6.0/journeymap.rendering.config"
hash = "adb365c27dcbf3a24b697cdb63f96bc6b09a179a2bea94397d146bdb890ac967"

[[files]]
file = "journeymap/config/6.0/journeymap.topo.config"
hash = "429c48cf38f5acb051b98ac7577e95fcf48b297d01cd83fd36e07c24c8416cad"

[[files]]
file = "journeymap/config/6.0/journeymap.waypoint.config"
hash = "a6e25c86ca2b8aa32a85829d7c39a31ccae7d749b240a55ea2000cb8cbcc490c"

[[files]]
file = "journeymap/config/6.0/journeymap.webmap.config"
hash = "6f472441a8c7377731ff5f9ad43f46951595c8a4969d1ba4b1055aa185a38c23"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "23fb3895299b959d4dc8852cd235c67a723cc43da4d7f8136d73c7b3256d28fa"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1bf302009fc75c3519ea095753fe926af91b0a2dce732d1775fa1920aca8e56a"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "57c4935e001e8d1688d226b0d54027395913aa861302d7c3307bf04ea1848392"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "72341600c6dc91dc11e1293a4fb87b594d9786c86b8e93b16680ea0973d92449"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "9b736b8bb0c8a36fd0cd84c258d2be0c504fd3719acd22875cf8506e4aae27aa"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "a8321c6d297c9a266a82600942a2b329f374abb9f3fdd0810499a2f26a082b2d"
metafile = true

[[files]]
file = "mods/better-selection.pw.toml"
hash = "ddb17abac95266f5845b2cc14acec1292e27f17da94acf423569b55f75ec8a7f"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "5a05b8c01319f72373ae725ce8ae531993ed3e44a55e19ae80a12224f5d27123"
metafile = true

[[files]]
file = "mods/betterstats.pw.toml"
hash = "c6b8af91f201644f75711d5605b15203c9bbfc986df00e1b17176628c1914a4d"
metafile = true

[[files]]
file = "mods/bridging-mod.pw.toml"
hash = "898a383ad33bb172ac111b2a038d383e02eae4c54fe25cbf3f0f11cc17eab5e5"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "c1ee4714f23846f70b6a150d965990264eda55a9e213c1baa8472a7be05a12f9"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "de8e021e0beacab839ca3bd4dfdb30fa5f3cfd1e71be722ccf56373908b41a7f"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "ebb83ff56fd213d1e0efb57d59a89a6c864c7be63436e028fec02878b300e426"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "f30a1a38054ad25b5105c463962c5b5fc53a070e0e860d4d7951208b333e3f7a"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a826fbce1a20169613e387719b40a05e95a0ca8ede805b82fa686533a0550713"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "b90a39972e2b4468f6b02127a1e370cd10a976fdae0d82527fa048e23e45b093"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "aba6398c78f281146fa114aafec5817ece9378d91e4bdd85213c95d50a7d4492"
metafile = true

[[files]]
file = "mods/detail-armor-bar-reconstructed.pw.toml"
hash = "35655c9869f280f3bb2d81ecf06041b7b2cd6a038655fbfb5a9bb776f015795f"
metafile = true

[[files]]
file = "mods/dynamic-crosshair.pw.toml"
hash = "c8664697b68d0bebcd029723591a146aa5bbcbf8c2c738ada4489ff69b6aedbc"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "3422a6b2866c352e063d9be97218ba3b51659b8c3f71ea0039c025e554e710b5"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "2864c89aa5d04d6f319bce5f6a0cbfc731512956c9acd59fafd3e1e5a1e9e7b6"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "0bf9d9a6ebe30362a010b209fed8b7bbd4a1104d680ffb8828597f9dc7605980"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "5453da0473b6a6c05cf248f06f4e7351377b467e0f4b022809a50671aafea199"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "1ee4bbb4b7df1a15737b48db1fa4a75e7205098701cbebd5da004faf6c6392a8"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "212a90f8ab7004e831d3a956c27f8fd522b894569e7e4d36268d894f00cf5583"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2acf991b9ab5eda85f595f5e91289116f3b14e5d4b3ee571a1068497754b91e2"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "1aa94f817646eea69478dc3dce662c3f4b674359d7ce34cf58fd38dcbc56e458"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "da4720149fabb3d338ff2d4d6eb59cb248e5210f8c515e2aa069731ff058c5d3"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "7217997480813cb423ad054d5765d8a1f92fae77542d327770336d6bd6eae554"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "47a38ead307c2d86ac06e12f70847dc0194da9014608d4ac7b4133ae6a5abdda"
metafile = true

[[files]]
file = "mods/first-person-model.pw.toml"
hash = "ed0e07891a0c790f2b0bddf4363f2012954659958b6002c170a3bc1c5a53023e"
metafile = true

[[files]]
file = "mods/forge-config-api-port-fabric.pw.toml"
hash = "3f793cb78a7b12af9f43914e55fd158789db5f69f69205a897e11cdd6569c367"
metafile = true

[[files]]
file = "mods/free-inventory.pw.toml"
hash = "fda3a1a98c7c1adc53e60bdc71b5607c92b62683d0a72fc77584cf234cbab868"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "064bb96880b86395a0493d055ea23af48d411c010635a9c8e14bd6f802a3e123"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "91402b8e46dac098bafe143b9dd36477f5e3230b4f2ff8cfcd68cf324b5f9c8d"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "2857a8dc942967be661710354790ccbd996f2c32d4b2c9ea7a5554ace3d98b97"
metafile = true

[[files]]
file = "mods/invmovecompats.pw.toml"
hash = "e08e7d05219d12b4de7083b2f7ec5424cf75d653e940633fff44d8def47db7e5"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "ee13368a3c2b3f834eb152a661e642455df50f4f5b1688f1c34626c4b01b6620"
metafile = true

[[files]]
file = "mods/itemphysic.pw.toml"
hash = "cf70760763ba76bf324d12b1f03145f53929343e387a325af407f2fb37ed822c"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "179047f50e0b2eb0fc669fded7c6a480441d7e8a0961453b2e21274c4d8f2e1c"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "c75fefbf0abf36da4f2de6e7da8d6988e9bc2301d0ada850755c86c5f315fe8e"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "9ff43b83964cac8079c9228ba9864222472e7ba3ff0a664144b3a35352012522"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "bcfd26bc56aa72b4edd5cd6a025137e51dc6cb4a7866a7665511009404d13bb9"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "2edafdc423051b21edbe49f433e73e6ba3164dfb079673355003e0f889e7ddf3"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "7f44fd433f995c8083c07ad9686b307b26691cc484e5ec41af2d1e4e7b5421fd"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "eb23a8bbd09621c14ce02a935573a6903125f9d8d92806152ebca8c16a5a9fd0"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "9a5062df61e09bf79936d0987a252aac26506b51d7c02107e4ca386c0c5a196c"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "0231d69e8d44350d5bb490b6c8d08f9b074397423cf68b61448f8528fdd19c42"
metafile = true

[[files]]
file = "mods/no-more-popups.pw.toml"
hash = "7a5d6a474afc81f35c56431a5a123ac567b85b2e01dbd928bee55816b94bb55f"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "56605167b88bb170da3643a32a810d51ce0a9c0c82e7b8f1dcbca4dfa909d8a6"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "2892ef637c93b1255b6ee01eab9b27afa27fe42664094130ba0d560c8a320713"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "4478b3a42925deadb386d54a10a37207d76dc6d6b5bb90e764e5a40f94bdb80f"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "bd5a56412de73022eba1895b1064ddd19362f188d8d0fd977ed208dfc18c041e"
metafile = true

[[files]]
file = "mods/roughly-enough-items.pw.toml"
hash = "24ec005442cecbe94a971c838eee430eef40b0bb15d4678a579436a5aaf9d865"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "2432429f4a67513150f12b44e5c6f67d9c4eb167e8c3b12ac5f3b136749bf293"
metafile = true

[[files]]
file = "mods/shoulder-surfing-reloaded.pw.toml"
hash = "cc6f92e78af23c38cfd07ace4459c965bc9e020939a9f6ef737dfa17bee8d752"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "e21e38581fe6bbe3d406905be4110ab60b9a8536bac2b9ef9257d7778734bf99"
metafile = true

[[files]]
file = "mods/skin-layers-3d.pw.toml"
hash = "d5b4d4d4e1191f459196b3c18d9ff7d71bc8e49a24f5df782ff2c3e800484f94"
metafile = true

[[files]]
file = "mods/skinshuffle.pw.toml"
hash = "d64c04590f64d9d60c735556b2b88d947907514c4b1e55bdf72ac02239e9ca9e"
metafile = true

[[files]]
file = "mods/smooth-scroll.pw.toml"
hash = "614ab32c2bfdecd7ea3ebd0f65afb06e2dd1c1e1009469ec3ad541a5068ec147"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "5269b2f8b0eb0ca98052d13cad6fe6417d13d064162fb1d95323626398c56587"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "cdf62992a654bf76495b999867271cd63f777e7af821ad2ca3f4099ccf58cd9d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "24aa12652da15e0e2d788a4cc2144ef908d6b4a792b644becd64ca3e1bfe4fe7"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "d15030e4fa60cde40cebe6764475fd4a7383b3a37e3a1e2a96461f7730ff1b6e"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "910452addf61893bacdcd8eb7659236a2fc4f57452a61ec3ecfe497abc74b4b2"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "27dc7fefde6ef779c53c2c517ab6992373c2266ca812661d65facf72e6bb31d0"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
hash = "c5fdf842ac50d5992853c9c6f073d876d358913b161498eb2f52b1de58d2a390"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "f49c6cc93bf7527571e4b756f5f5632a198de48a3930482a7d9c231360fa6348"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "74c920cae58e2e159507b6d1c2e7485d4e628368e33593c1ddaef03b9c669ff9"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "95351a8e1eacbfe181024d281f5b87c93dd545319a21b5dd30ba45e4c8a94678"
metafile = true

[[files]]
file = "options.txt"
hash = "ebd49372bf41fb8c30574c3bcf4c41b9032d5f42a8b7ef93548faa632628fc2f"

[[files]]
file = "resourcepacks/better-ipn-buttons.pw.toml"
hash = "344cfb1bf3259c3534dc0b0737aef164f0f3c97ddf75f15fd564fbd93c427c0d"
metafile = true

[[files]]
file = "resourcepacks/connected-bricks.pw.toml"
hash = "d2fb7fe13cb628eb286b5de89e70053644a5582df7816d7193bec14e7880db48"
metafile = true

[[files]]
file = "resourcepacks/connected-paths.pw.toml"
hash = "7174fb1f875a66d62b981bfe107d9a362700086212dfbb2be8993c9eacb2dcf2"
metafile = true

[[files]]
file = "resourcepacks/connected-rocks.pw.toml"
hash = "51c4f91bfa273b8115f404435d58f99d56088141f869083a7de2bc82655b680d"
metafile = true

[[files]]
file = "resourcepacks/eating-animation-resource-pack.pw.toml"
hash = "5da2d254ce79909463b3a1e655fd1ecab89449ec6c6f7f5e014b164263a9cd35"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "2d8aab62e51d84e33920e15cdd34fd164d971b01aede0c3d17abcd08117d33a9"
metafile = true

[[files]]
file = "resourcepacks/fast-better-grass.pw.toml"
hash = "5310da73a0fb83b049f5e5a3fdd82c73873da024d0ce663a2365c209c002fd0a"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "72b919a0242253a1540a0fa424ea5a652787365186ac9f5fa5a67583bb5d368c"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "9532816a020467d30459bbd3f42806916ffd33f79b1fdbae5e7b25a3af71a372"
metafile = true

[[files]]
file = "resourcepacks/minecraft-3d-default.pw.toml"
hash = "b7e15b60c2dc789a55abec62321393ddcb349c4e6f14646b24a0f07fc7bb6df5"
metafile = true

[[files]]
file = "resourcepacks/recolourful-containers-gui-hud-dark.pw.toml"
hash = "91d9ebebc72f713caf3c181839d2966190e3018fdcf87fd02ffa94e1244cf6df"
metafile = true

[[files]]
file = "resourcepacks/torches-reimagined.pw.toml"
hash = "24ac06885ef01025f8abe7d57ae0452bb18ca9eba084092ce2fc444f6272da58"
metafile = true

[[files]]
file = "resourcepacks/translations-for-sodium.pw.toml"
hash = "701813f85a323e9d5609dc31c911f5872dfb8a69a8ff753c113046e927cd5d1e"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "006170836f3180d229a6b95e1b33c060d7afcd0755273669faf78e86f50579ed"
metafile = true
