name = "Net Play MC"
author = "Alfakynz"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "faa34dccdce4a3803e95c53da078b6ba2cfb8c8a200287828f46ea555c223b6c"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
