name = "Net Play MC"
author = "Alfakynz"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "302f5eab368243ce23092fffc394ea55ad69281ca3fef5421772dfa06f4870ec"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
