hash-format = "sha256"

[[files]]
file = "config/betterf3.json"
hash = "0028abb010568e5d31c2d12390a18a471a495591a24bf408abea3c151e8d234e"

[[files]]
file = "config/detailarmorbar.json"
hash = "a5c688952ee55d6ac48c632baa5667d8adc20758ab2fd6c913c1b411bb4cad71"

[[files]]
file = "config/euphoria_patcher.properties"
hash = "66793f6eb032dba20841b7b015cf96550baec9686ee9cf758edc2e41b193ec25"

[[files]]
file = "config/inventoryprofilesnext/inventoryprofiles.json"
hash = "3b2f0b16fe70aa6a7720622bf7dcb99e59e412c37169763b3af0c8b310b74d5e"

[[files]]
file = "config/iris.properties"
hash = "4eb525ec220ff749911e5d1f8f6eab09ec9d78875dd4baf6d63e6a50ba069ac0"

[[files]]
file = "config/jade/jade.json"
hash = "93e098f8882bbfe9eaba05694016fff55a911114d1cea2a046915e6f4253d64b"

[[files]]
file = "config/jade/plugins.json"
hash = "8daf20878a02aab8611856f409ea0b33f721ef1d5be4bad4053d446e9634ba28"

[[files]]
file = "config/no-more-popups.json"
hash = "31e5140ee7bb35c73c8ae74eb785eca3c81caf235d467fd4a38e75e86e0a6aa7"

[[files]]
file = "config/roughlyenoughitems/config.json5"
hash = "e20428580f54cb128b11bb54b38b4c9957473f5494628bcf42c7c358276f9759"

[[files]]
file = "config/rrls.toml"
hash = "e640a0284af42c946e5495440466beae329f32f9b7aa068a9d1d51559b9624f8"

[[files]]
file = "config/shouldersurfing-client.toml"
hash = "880d1725e8bc4b9a4fb2753a5d698fa380d822afb007cd92d618e7254ea3ff33"

[[files]]
file = "config/skinshuffle/config.json"
hash = "662c8542ea661fc5321a22e99df6dafd0d6055ed0416a3fc767df130a9953a52"

[[files]]
file = "config/voicechat/voicechat-client.properties"
hash = "565252c49707cbd0503824432c6cde64739eaa56130c1d3b8096c6754ca25853"

[[files]]
file = "icon.png"
hash = "c36c0efbe5be0b9cf0fdfe54dbe17bea53295ac2a372d1203aa0f5c9c68d2bc7"

[[files]]
file = "journeymap/config/6.0/journeymap.core.config"
hash = "f186361722ed93165d61b42169ee0495310f7032b32a77f0f09c34f1c8dff6e3"

[[files]]
file = "journeymap/config/6.0/journeymap.fullmap.config"
hash = "b767cc9b4c8f8aadd2f07e03af345b51a44077d5a5c9d6ff491d57f0bb5d2e32"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap.config"
hash = "8cda76eb64346eb0b4c4fd567aa32b8a2c752a6600170db33729568ef0f7ad70"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap2.config"
hash = "26fd46b816044dbbc8fbd5fca1514b77598db69d3c239195edf0d7a40f969685"

[[files]]
file = "journeymap/config/6.0/journeymap.rendering.config"
hash = "adb365c27dcbf3a24b697cdb63f96bc6b09a179a2bea94397d146bdb890ac967"

[[files]]
file = "journeymap/config/6.0/journeymap.topo.config"
hash = "429c48cf38f5acb051b98ac7577e95fcf48b297d01cd83fd36e07c24c8416cad"

[[files]]
file = "journeymap/config/6.0/journeymap.waypoint.config"
hash = "a6e25c86ca2b8aa32a85829d7c39a31ccae7d749b240a55ea2000cb8cbcc490c"

[[files]]
file = "journeymap/config/6.0/journeymap.webmap.config"
hash = "6f472441a8c7377731ff5f9ad43f46951595c8a4969d1ba4b1055aa185a38c23"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "afff0dca3236e95f4680f2faff03b52b4ac9ee4b0d222b9a3084a14160a0bf9d"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1bf302009fc75c3519ea095753fe926af91b0a2dce732d1775fa1920aca8e56a"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "c595e47763e635e74248cf3f0a9eefdc14b3fe430b6e3e23e331da3c7f85533c"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "72341600c6dc91dc11e1293a4fb87b594d9786c86b8e93b16680ea0973d92449"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "63963e365505f6639234033b1c19061ae28577140969f8de475a2d384ed55e3a"
metafile = true

[[files]]
file = "mods/better-selection.pw.toml"
hash = "ddb17abac95266f5845b2cc14acec1292e27f17da94acf423569b55f75ec8a7f"
metafile = true

[[files]]
file = "mods/better-slots.pw.toml"
hash = "7381967b1386650fb90df85d345dc78116adc858e10352549d34671256f2bd69"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "5a05b8c01319f72373ae725ce8ae531993ed3e44a55e19ae80a12224f5d27123"
metafile = true

[[files]]
file = "mods/betterstats.pw.toml"
hash = "b2ab196fc5f8632b9ace1984ae4b718e680ee31e33af3ebce28440b3d7ceac08"
metafile = true

[[files]]
file = "mods/bridging-mod.pw.toml"
hash = "898a383ad33bb172ac111b2a038d383e02eae4c54fe25cbf3f0f11cc17eab5e5"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "18a58c448f9c1c558bb37ea711f50333aeaa0b26f8fa268e3c38b23713a49935"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "de8e021e0beacab839ca3bd4dfdb30fa5f3cfd1e71be722ccf56373908b41a7f"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "f30a1a38054ad25b5105c463962c5b5fc53a070e0e860d4d7951208b333e3f7a"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a826fbce1a20169613e387719b40a05e95a0ca8ede805b82fa686533a0550713"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "d3f0d7a0cfaece0b2bb3bd2a14af468590835bbfd7d276ba2c4b6bec77e69247"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "aba6398c78f281146fa114aafec5817ece9378d91e4bdd85213c95d50a7d4492"
metafile = true

[[files]]
file = "mods/detail-armor-bar-reconstructed.pw.toml"
hash = "f196edcd302253c361531537a1eca6d041a464b445595aea0b354694d4d4289c"
metafile = true

[[files]]
file = "mods/dynamic-crosshair.pw.toml"
hash = "c8664697b68d0bebcd029723591a146aa5bbcbf8c2c738ada4489ff69b6aedbc"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "3422a6b2866c352e063d9be97218ba3b51659b8c3f71ea0039c025e554e710b5"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "2864c89aa5d04d6f319bce5f6a0cbfc731512956c9acd59fafd3e1e5a1e9e7b6"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "0bf9d9a6ebe30362a010b209fed8b7bbd4a1104d680ffb8828597f9dc7605980"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "5453da0473b6a6c05cf248f06f4e7351377b467e0f4b022809a50671aafea199"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "f40522755246c7e247a3580bcd9b5e1a7ccea6c2133bcc686f7afe3aedaeb9ab"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "212a90f8ab7004e831d3a956c27f8fd522b894569e7e4d36268d894f00cf5583"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "f992c07d24f87f0368b22d62ffaa34865d4146b1c1aa34f5618a06a114aab53f"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "1aa94f817646eea69478dc3dce662c3f4b674359d7ce34cf58fd38dcbc56e458"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "da4720149fabb3d338ff2d4d6eb59cb248e5210f8c515e2aa069731ff058c5d3"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "7217997480813cb423ad054d5765d8a1f92fae77542d327770336d6bd6eae554"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "47a38ead307c2d86ac06e12f70847dc0194da9014608d4ac7b4133ae6a5abdda"
metafile = true

[[files]]
file = "mods/first-person-model.pw.toml"
hash = "b9a35ffb7139f047db5bd78febe6976091bff24888a6cc51ade3c9001aeb934d"
metafile = true

[[files]]
file = "mods/forge-config-api-port-fabric.pw.toml"
hash = "adc3586c1907ab5672119dec308e2f107aa45af1b528bfc6fb1be736bdc11a63"
metafile = true

[[files]]
file = "mods/free-inventory.pw.toml"
hash = "542942091bf1e47f4532bffb12f880ccb66c65f6f7c91140d04609e0eef29694"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "064bb96880b86395a0493d055ea23af48d411c010635a9c8e14bd6f802a3e123"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "449e1ead35963eb60b6d6fdd2d1da759dbd621262b31ce6d6fe68e3a828ba062"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "a2916d3b634fc0a51037d10b097e52fa154046f642146cf54b6c081a4512cfeb"
metafile = true

[[files]]
file = "mods/invmovecompats.pw.toml"
hash = "e08e7d05219d12b4de7083b2f7ec5424cf75d653e940633fff44d8def47db7e5"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "427b4d017b83401708e96e36f11f11c7474365011b108b255f69e000ecc6422c"
metafile = true

[[files]]
file = "mods/itemphysic-lite.pw.toml"
hash = "6f55c0d6abed98ee255af3660fbf7f5dd531c1b54f6d42d24c67dd872a6b966e"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "179047f50e0b2eb0fc669fded7c6a480441d7e8a0961453b2e21274c4d8f2e1c"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "bada7d53b0a38c74c7299f193064ab1ffd3b538c5d518ac0de3d177919c0e9f3"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "4ea0e9acbc8f7b15eb2490049543d022793969f9c88f346cfadaec969daa94e7"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "efc7ac731dc593881f15920d5c4ff7ab96c2ca2d8517de459c549fef14f9ca9c"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "2edafdc423051b21edbe49f433e73e6ba3164dfb079673355003e0f889e7ddf3"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "b9bb98767d6b26fd16a123020eb04b50e6ff575a5bfa37bd84247201bf05d143"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "eb23a8bbd09621c14ce02a935573a6903125f9d8d92806152ebca8c16a5a9fd0"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "9a5062df61e09bf79936d0987a252aac26506b51d7c02107e4ca386c0c5a196c"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "0231d69e8d44350d5bb490b6c8d08f9b074397423cf68b61448f8528fdd19c42"
metafile = true

[[files]]
file = "mods/no-more-popups.pw.toml"
hash = "7a5d6a474afc81f35c56431a5a123ac567b85b2e01dbd928bee55816b94bb55f"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "05ef0e40a80bd0c0b42ccd8919efc7243b3a9d2a04310a33dc47fddc5bf79a29"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "2892ef637c93b1255b6ee01eab9b27afa27fe42664094130ba0d560c8a320713"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "800e2612154c9f5648f831058bb29e2cd09cc751625bad15191ca138e272acab"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "bd5a56412de73022eba1895b1064ddd19362f188d8d0fd977ed208dfc18c041e"
metafile = true

[[files]]
file = "mods/roughly-enough-items.pw.toml"
hash = "7fbb6f1678e1f1c494ee16edf325be4488c4c9f10ad598a46bb6f101c5d1f899"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "2432429f4a67513150f12b44e5c6f67d9c4eb167e8c3b12ac5f3b136749bf293"
metafile = true

[[files]]
file = "mods/shoulder-surfing-reloaded.pw.toml"
hash = "cc6f92e78af23c38cfd07ace4459c965bc9e020939a9f6ef737dfa17bee8d752"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "337016e755039f8ca86f22561ac11516b32c188a5daf9bb1cc13dfe8c4ab5d18"
metafile = true

[[files]]
file = "mods/skin-layers-3d.pw.toml"
hash = "fb012b2d544560ae82b7bfa09f2716aaafc3890ba7fc0f5183f23b723292d2a8"
metafile = true

[[files]]
file = "mods/skinshuffle.pw.toml"
hash = "d64c04590f64d9d60c735556b2b88d947907514c4b1e55bdf72ac02239e9ca9e"
metafile = true

[[files]]
file = "mods/smooth-scroll.pw.toml"
hash = "614ab32c2bfdecd7ea3ebd0f65afb06e2dd1c1e1009469ec3ad541a5068ec147"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "5269b2f8b0eb0ca98052d13cad6fe6417d13d064162fb1d95323626398c56587"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "cdf62992a654bf76495b999867271cd63f777e7af821ad2ca3f4099ccf58cd9d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "24aa12652da15e0e2d788a4cc2144ef908d6b4a792b644becd64ca3e1bfe4fe7"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "65a0aff6547f652037019ee0edbe02e2fb6fbcb6fe3e3e99641f59920e636422"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "910452addf61893bacdcd8eb7659236a2fc4f57452a61ec3ecfe497abc74b4b2"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "d66ef07cc0b0c840c843bd6dd2e09b138ecc90a844fb1854f94d46e23d827609"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
hash = "0787ab6531801c24e341fcfc10459dfd3229a3b5a13fb89fde00f1d957a0ae12"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "f49c6cc93bf7527571e4b756f5f5632a198de48a3930482a7d9c231360fa6348"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "6d002495de7af2cf384c8fbc9c86f8b9b257bee0f12b2144e6e6a7b60827ee1c"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "2476f7001c44c072f82a7cf1559bb9bf90beb37bcba2dcb2b11b6efe89f2b705"
metafile = true

[[files]]
file = "options.txt"
hash = "ebd49372bf41fb8c30574c3bcf4c41b9032d5f42a8b7ef93548faa632628fc2f"

[[files]]
file = "resourcepacks/better-ipn-buttons.pw.toml"
hash = "344cfb1bf3259c3534dc0b0737aef164f0f3c97ddf75f15fd564fbd93c427c0d"
metafile = true

[[files]]
file = "resourcepacks/connected-bricks.pw.toml"
hash = "d2fb7fe13cb628eb286b5de89e70053644a5582df7816d7193bec14e7880db48"
metafile = true

[[files]]
file = "resourcepacks/connected-paths.pw.toml"
hash = "7174fb1f875a66d62b981bfe107d9a362700086212dfbb2be8993c9eacb2dcf2"
metafile = true

[[files]]
file = "resourcepacks/connected-rocks.pw.toml"
hash = "51c4f91bfa273b8115f404435d58f99d56088141f869083a7de2bc82655b680d"
metafile = true

[[files]]
file = "resourcepacks/eating-animation-resource-pack.pw.toml"
hash = "5da2d254ce79909463b3a1e655fd1ecab89449ec6c6f7f5e014b164263a9cd35"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "2d8aab62e51d84e33920e15cdd34fd164d971b01aede0c3d17abcd08117d33a9"
metafile = true

[[files]]
file = "resourcepacks/fast-better-grass.pw.toml"
hash = "5310da73a0fb83b049f5e5a3fdd82c73873da024d0ce663a2365c209c002fd0a"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "72b919a0242253a1540a0fa424ea5a652787365186ac9f5fa5a67583bb5d368c"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "9532816a020467d30459bbd3f42806916ffd33f79b1fdbae5e7b25a3af71a372"
metafile = true

[[files]]
file = "resourcepacks/minecraft-3d-default.pw.toml"
hash = "b7e15b60c2dc789a55abec62321393ddcb349c4e6f14646b24a0f07fc7bb6df5"
metafile = true

[[files]]
file = "resourcepacks/recolourful-containers-gui-hud-dark.pw.toml"
hash = "91d9ebebc72f713caf3c181839d2966190e3018fdcf87fd02ffa94e1244cf6df"
metafile = true

[[files]]
file = "resourcepacks/torches-reimagined.pw.toml"
hash = "24ac06885ef01025f8abe7d57ae0452bb18ca9eba084092ce2fc444f6272da58"
metafile = true

[[files]]
file = "resourcepacks/translations-for-sodium.pw.toml"
hash = "c8e0537a809bd784b937c5941182a1ad148810e3c7c5aad505a80e8364c5d64f"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "006170836f3180d229a6b95e1b33c060d7afcd0755273669faf78e86f50579ed"
metafile = true
