name = "Net Play MC"
author = "Alfakynz"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ff71a83090e696f4eda107cf02208e82c804cecaedf0bbce05f17bdc751d3b9"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
