hash-format = "sha256"

[[files]]
file = "config/betterf3.json"
hash = "0028abb010568e5d31c2d12390a18a471a495591a24bf408abea3c151e8d234e"

[[files]]
file = "config/detailarmorbar.json"
hash = "a5c688952ee55d6ac48c632baa5667d8adc20758ab2fd6c913c1b411bb4cad71"

[[files]]
file = "config/euphoria_patcher.properties"
hash = "66793f6eb032dba20841b7b015cf96550baec9686ee9cf758edc2e41b193ec25"

[[files]]
file = "config/inventoryprofilesnext/inventoryprofiles.json"
hash = "3b2f0b16fe70aa6a7720622bf7dcb99e59e412c37169763b3af0c8b310b74d5e"

[[files]]
file = "config/iris.properties"
hash = "4eb525ec220ff749911e5d1f8f6eab09ec9d78875dd4baf6d63e6a50ba069ac0"

[[files]]
file = "config/jade/jade.json"
hash = "93e098f8882bbfe9eaba05694016fff55a911114d1cea2a046915e6f4253d64b"

[[files]]
file = "config/jade/plugins.json"
hash = "8daf20878a02aab8611856f409ea0b33f721ef1d5be4bad4053d446e9634ba28"

[[files]]
file = "config/no-more-popups.json"
hash = "31e5140ee7bb35c73c8ae74eb785eca3c81caf235d467fd4a38e75e86e0a6aa7"

[[files]]
file = "config/roughlyenoughitems/config.json5"
hash = "e20428580f54cb128b11bb54b38b4c9957473f5494628bcf42c7c358276f9759"

[[files]]
file = "config/rrls.toml"
hash = "e640a0284af42c946e5495440466beae329f32f9b7aa068a9d1d51559b9624f8"

[[files]]
file = "config/shouldersurfing-client.toml"
hash = "880d1725e8bc4b9a4fb2753a5d698fa380d822afb007cd92d618e7254ea3ff33"

[[files]]
file = "config/skinshuffle/config.json"
hash = "662c8542ea661fc5321a22e99df6dafd0d6055ed0416a3fc767df130a9953a52"

[[files]]
file = "config/voicechat/voicechat-client.properties"
hash = "565252c49707cbd0503824432c6cde64739eaa56130c1d3b8096c6754ca25853"

[[files]]
file = "icon.png"
hash = "c36c0efbe5be0b9cf0fdfe54dbe17bea53295ac2a372d1203aa0f5c9c68d2bc7"

[[files]]
file = "journeymap/config/6.0/journeymap.core.config"
hash = "f186361722ed93165d61b42169ee0495310f7032b32a77f0f09c34f1c8dff6e3"

[[files]]
file = "journeymap/config/6.0/journeymap.fullmap.config"
hash = "b767cc9b4c8f8aadd2f07e03af345b51a44077d5a5c9d6ff491d57f0bb5d2e32"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap.config"
hash = "8cda76eb64346eb0b4c4fd567aa32b8a2c752a6600170db33729568ef0f7ad70"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap2.config"
hash = "26fd46b816044dbbc8fbd5fca1514b77598db69d3c239195edf0d7a40f969685"

[[files]]
file = "journeymap/config/6.0/journeymap.rendering.config"
hash = "adb365c27dcbf3a24b697cdb63f96bc6b09a179a2bea94397d146bdb890ac967"

[[files]]
file = "journeymap/config/6.0/journeymap.topo.config"
hash = "429c48cf38f5acb051b98ac7577e95fcf48b297d01cd83fd36e07c24c8416cad"

[[files]]
file = "journeymap/config/6.0/journeymap.waypoint.config"
hash = "a6e25c86ca2b8aa32a85829d7c39a31ccae7d749b240a55ea2000cb8cbcc490c"

[[files]]
file = "journeymap/config/6.0/journeymap.webmap.config"
hash = "6f472441a8c7377731ff5f9ad43f46951595c8a4969d1ba4b1055aa185a38c23"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "a48ad9b6bb9d67ecf2070f8eabd0d33107d50cae9700d764c6300d0a6084efa7"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "e4871feb4abc954731ceb980476dd7500357f689daf5d9e4065c0f70aad18d03"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "b5b0ae54a96d2a7a40c9077a3385df4a0c2564d86a0dfb27bc4300390e14194b"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "02a609de09efd7cadb420e44e392d6b48d62ec92ffefcbef4af4511bc8b33ac2"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "27725428090c668a19c50483c33d5fffe5908c4e97f056ebbd43c957337ea190"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "177df578f177b18dcbdc6dca4ea74931903443cd8afbbc11d879a48bf07d5264"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "a8321c6d297c9a266a82600942a2b329f374abb9f3fdd0810499a2f26a082b2d"
metafile = true

[[files]]
file = "mods/better-selection.pw.toml"
hash = "5f13e2470d769f613652ff4378a31c86b5915fe67032c94c1be5aeed06610b4d"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "511a5c89a7a95d63c60733fd0b422e8cb3b788f60f386228ec714c3a3254905d"
metafile = true

[[files]]
file = "mods/betterstats.pw.toml"
hash = "1cdb2db8964cb12942e4872de62468296e56548119fad1e406d88bc9b0ccb870"
metafile = true

[[files]]
file = "mods/bridging-mod.pw.toml"
hash = "8e6e2382cd2502b793fc7a1b412aced4ae31825e345af69e5717ec44d694d883"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "cb21f2c93b3f21865cd2a09de40d9541a8b172480b9162f6cb4c57853f4fad4f"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "7621c38bf5eb90cc7458a78eeab30088bae4bf9f29f72bbc2a2a7c37fc06b551"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "3357a0f5f06655080447c8a06bc20b531783193696868360f41e7b19adbdf03c"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "dd3fee4cb3fb078b09fc89d958b00aa65c42ad10fca267c97c66d2bc81dd9814"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a826fbce1a20169613e387719b40a05e95a0ca8ede805b82fa686533a0550713"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "eb80b3fd7da59624e25cbefbbef5646c538886638d8e556ec2dfa7dade4e0444"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "aba6398c78f281146fa114aafec5817ece9378d91e4bdd85213c95d50a7d4492"
metafile = true

[[files]]
file = "mods/detail-armor-bar-reconstructed.pw.toml"
hash = "f4c6a51debdf1dae53f49bc87cbf878eb16150cf1c2d9e260f29077665833ba4"
metafile = true

[[files]]
file = "mods/dynamic-crosshair.pw.toml"
hash = "54237d910ebdbd023e4969f0e83b1106c381329174816aed2e0ec2cc92d73f5b"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "4741f6b6190614414c2289db39b60e822a3172c412db122a23c67ece2ba92494"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "2864c89aa5d04d6f319bce5f6a0cbfc731512956c9acd59fafd3e1e5a1e9e7b6"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "f6e8aa647b533f104b6d03b3a2872801f0d2ddcff27cd62c2d9a048ca7daf85a"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "96cba2fc1c49c5232d43212e5f4e9b724b0046169345cdafec63e8c41e49aa34"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "62ca78f72f0c5de86e65ca7dd5c356c1f6ae406cee10361d9c26db45a244f195"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "212a90f8ab7004e831d3a956c27f8fd522b894569e7e4d36268d894f00cf5583"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "f8936bef75675978cec779563c24358db371e3c3e8700e082a2707ce81801522"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "1aa94f817646eea69478dc3dce662c3f4b674359d7ce34cf58fd38dcbc56e458"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "372c23d9de8c88dfe61efccc6639f077ad9b8188647f80bedea99fd02e721dc1"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "cdf5789bfb1d68fd1cfe6ed914ef098e46bc777fda3a42b3e62a2fbe2656315e"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "3dcc43cbc807ec49377efe574b4670ee91e62474aee1bcd068495adea8bc1f6a"
metafile = true

[[files]]
file = "mods/first-person-model.pw.toml"
hash = "b218c44f07ac7e328e4a6c68349da678d310170c6f4229a7a1691840f1a0d0e0"
metafile = true

[[files]]
file = "mods/forge-config-api-port-fabric.pw.toml"
hash = "21052c0adce37ff045717e0340dcc9f8973f6caf5ef5a119d0f32b37d4fdb9a0"
metafile = true

[[files]]
file = "mods/free-inventory.pw.toml"
hash = "a1396d8ed31795e01d54e16b25aa4b61ffbc2d4790b087faaaf2c1282dc1be6a"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "4283540140b64d603376f1212f565a8721ca553dd456c8b62c85076cda6e7b09"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "59489be1897040348413e05bbb8c33db52434bcd5f77769aa894061351e6fb0b"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "942d4ab5b57d6a660454133135d863a9272e1de7b825aa3242508722dffa7366"
metafile = true

[[files]]
file = "mods/invmovecompats.pw.toml"
hash = "c5732bb80de9248a43375a6a9d22d71066b4e5ec06d2829c1dbb80d4a84eec47"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "d93b46b247fe2a2a3a70638c66fa73618d46cad43aeb7df0d90f5311ba2de280"
metafile = true

[[files]]
file = "mods/itemphysic.pw.toml"
hash = "b5a955fc7d50b7a2fe4277f6f4f57a628ead6fa63c919d658f802ca2fb464cf7"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "d0e03ecd9455c3aa1782b35d0d1a93014982a3fc2aa03c42fb216e1dd7d1a17c"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "ba0b53e4650ac82b1c09bd31409319705b6b3ecbb63f93a83a2b2ba78654a87e"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "3ba36e736300521785ffce9b2586c363cea9d0a302bde1d98e1d613288e91df1"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c7615a718c4db7c8bad89d181e1d9a1e5f8a534bd1dc95c77e26b0af9c34c18a"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "2edafdc423051b21edbe49f433e73e6ba3164dfb079673355003e0f889e7ddf3"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "474dbec1a749b8a1af2504bf0380c77a3f5815ba4038614b91b873aae2fe57d8"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "04bffe7613a3a9d7592c8dca2399556ce74ba7049e115827ad80888f9bda7672"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "cf7020c5a0575299d31f3d116ea25221cc7d0a0e83ed10cd78e33830766525b4"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "f44cb40ee8751e97fb9379befdaef5034636170e0f0d7b6bcf46672f713d848d"
metafile = true

[[files]]
file = "mods/no-more-popups.pw.toml"
hash = "7a5d6a474afc81f35c56431a5a123ac567b85b2e01dbd928bee55816b94bb55f"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "6e2ef6b59e82526f8c05c827757bcec8ac08b9186eaffbce13879833443267cc"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "15aaf7df5b2bef18a75f33cffd046700cd58191b662c2f9f05884d78605df87a"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "9eac5f903d01b7a6d629d15e19cfcea6fe52966fa072a20c4e3ce642f85bac79"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "56390b7b5a7815868460b7f489b8bafba913652bb10a9f8383cefba1a483a15f"
metafile = true

[[files]]
file = "mods/roughly-enough-items.pw.toml"
hash = "067338009da5e8f1552cc0dea032a02b6d96e9a94b8a6cea7b63fe5bbc52b97c"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "ca77ce40de8c648ddd61e5b4fd434fab8cf305f36c923fe993cb6ed4e112d46e"
metafile = true

[[files]]
file = "mods/shoulder-surfing-reloaded.pw.toml"
hash = "808f4e2589c3af7ca42cbdad68f0bb51b1059044f22d94ad3f58f4367d49641a"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "e731ece402577fdef4086f795aeba338461264651935702feee0a826d3205f2d"
metafile = true

[[files]]
file = "mods/skin-layers-3d.pw.toml"
hash = "a949687cfe1a864a6dfd84b770d05f498bd59330d263d8e7318bf730fcf8acf5"
metafile = true

[[files]]
file = "mods/skinshuffle.pw.toml"
hash = "f5f28a838f7164aac2d3aafb0734a6bbd1ba3e6cf0bb0626f62347c5ee15dfd1"
metafile = true

[[files]]
file = "mods/smooth-scroll.pw.toml"
hash = "5106847bd76f1cb69d9c88fe1a907f9f58b740edf59e7c660c18e11e95b34cb0"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "e2d0b41a222e16c3819deb9aef6301020770b213f197493746c70cfffb304901"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "cdf62992a654bf76495b999867271cd63f777e7af821ad2ca3f4099ccf58cd9d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "e22254a6f9d2eb28da5e503e48faaf9f6767e6485f8607b449713a461e850d46"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "32a9be0cc40707141a7f0601a8fc39f06478d316e4971f80430dd71c2038b8ad"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "152700bab5942f9d06f25eec6254bd2c2d2a97341cf994fd73a81b4eeb030fb0"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "72d29f4e46b30780c42db3d30245328eef81a7e8453c44d7892fc8b7b0bbb0ba"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
hash = "82cc41c439575118a33c9bbbd35c136762d81a167d097a0adf62db94dbd43238"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "d8e3de0893d8f51f20589d62fced17eb56a5a70248cab6bfe68cd7a541ee4d8b"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "3ccb5713e745db48dfcb6174853161d8fed60ecbdf770dc78ae5663f5b04f352"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "c41c88bf75d26b2b5eda3254ebfef62a6e8625d75c2a80cfe1207c95b9de2c5f"
metafile = true

[[files]]
file = "options.txt"
hash = "ebd49372bf41fb8c30574c3bcf4c41b9032d5f42a8b7ef93548faa632628fc2f"

[[files]]
file = "resourcepacks/better-ipn-buttons.pw.toml"
hash = "344cfb1bf3259c3534dc0b0737aef164f0f3c97ddf75f15fd564fbd93c427c0d"
metafile = true

[[files]]
file = "resourcepacks/connected-bricks.pw.toml"
hash = "2dd6eab43c3770d6e5129bc2b2003dd4f5f297f3f831b59f2942dc1c3726897f"
metafile = true

[[files]]
file = "resourcepacks/connected-paths.pw.toml"
hash = "a48c0063313ca6bb027668a668f95f7460a37929656f4fc5b6ad7cf5c228d187"
metafile = true

[[files]]
file = "resourcepacks/connected-rocks.pw.toml"
hash = "86c9ec0b0d0d1cc3226f40116e25bb573e987d905bde72c81644e19ef9d4dc51"
metafile = true

[[files]]
file = "resourcepacks/eating-animation-resource-pack.pw.toml"
hash = "5da2d254ce79909463b3a1e655fd1ecab89449ec6c6f7f5e014b164263a9cd35"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "2d8aab62e51d84e33920e15cdd34fd164d971b01aede0c3d17abcd08117d33a9"
metafile = true

[[files]]
file = "resourcepacks/fast-better-grass.pw.toml"
hash = "5310da73a0fb83b049f5e5a3fdd82c73873da024d0ce663a2365c209c002fd0a"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "72b919a0242253a1540a0fa424ea5a652787365186ac9f5fa5a67583bb5d368c"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "e5ff336f3fd1788342d65ac441e5bb54f83b2925b3798ad9f8ec992119d8f5e3"
metafile = true

[[files]]
file = "resourcepacks/minecraft-3d-default.pw.toml"
hash = "b7e15b60c2dc789a55abec62321393ddcb349c4e6f14646b24a0f07fc7bb6df5"
metafile = true

[[files]]
file = "resourcepacks/recolourful-containers-gui-hud-dark.pw.toml"
hash = "91d9ebebc72f713caf3c181839d2966190e3018fdcf87fd02ffa94e1244cf6df"
metafile = true

[[files]]
file = "resourcepacks/torches-reimagined.pw.toml"
hash = "24ac06885ef01025f8abe7d57ae0452bb18ca9eba084092ce2fc444f6272da58"
metafile = true

[[files]]
file = "resourcepacks/translations-for-sodium.pw.toml"
hash = "701813f85a323e9d5609dc31c911f5872dfb8a69a8ff753c113046e927cd5d1e"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "006170836f3180d229a6b95e1b33c060d7afcd0755273669faf78e86f50579ed"
metafile = true
