name = "Net Play MC"
author = "Alfakynz"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19cd3d5213eb2e016f7e9577934f08c3b150a9e21643fb01560b64c9aea5791e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.6"]
