name = "Net Play MC"
author = "Alfakynz"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c503f942f48a70cb334892ab88a7f89dc3717d1bd2828c65e5e9e19c9d25e8ed"

[versions]
fabric = "0.18.2"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.6"]
