name = "Net Play MC"
author = "Alfakynz"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a1baeff5bb9402c18e199aff4997e2a22b246466e253f7fe905bcd4d2f80331"

[versions]
fabric = "0.18.4"
minecraft = "1.21.5"
