name = "Net Play MC"
author = "Alfakynz"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80000adf1fb71cb864c9b2062c2b933ee664156da5c7e3f282e577896d2abe8f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.5"
