name = "Net Play MC"
author = "Alfakynz"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bbc2de1fd02f1624bce301212da416e6a3efb6ba0b3b130e705481497f44e45"

[versions]
fabric = "0.18.4"
minecraft = "1.21.8"
