name = "Net Play MC"
author = "Alfakynz"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea4bcfaf04fb0f65d434737f483cf5517cc18970287f0d0e617af28b7ab27779"

[versions]
fabric = "0.18.4"
minecraft = "1.21.8"
