name = "Net Play MC"
author = "Alfakynz"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83e374e07e137c949f0901e2e7cc0b09c23fe7da91f8b9dc9f03e75cc5b8c443"

[versions]
fabric = "0.18.2"
minecraft = "1.21.8"
