name = "Net Play MC"
author = "Alfakynz"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6100a03a051d2097a0a3e6883329d46b5c455177c1eaadd256f79c22d14da85"

[versions]
fabric = "0.18.2"
minecraft = "1.21.8"
