hash-format = "sha256"

[[files]]
file = "config/betterf3.json"
hash = "0028abb010568e5d31c2d12390a18a471a495591a24bf408abea3c151e8d234e"

[[files]]
file = "config/euphoria_patcher.properties"
hash = "66793f6eb032dba20841b7b015cf96550baec9686ee9cf758edc2e41b193ec25"

[[files]]
file = "config/inventoryprofilesnext/integrationHints/exampleIntegrationHints.json"
hash = "ca413dea02cce69c69dccdc525fb0ec013236876eff2d142772c68db3d772d3a"

[[files]]
file = "config/inventoryprofilesnext/inventoryprofiles.json"
hash = "cc6948c287851fdb08146d86250841e4d6ee9c802ebba1f8df13aa3445528be0"

[[files]]
file = "config/jade/hide-blocks.json"
hash = "309df4ae96864c19eae41b646d58497c85a73b1fc3c584e772ef4d5822794baa"

[[files]]
file = "config/jade/hide-entities.json"
hash = "3741bb54a4535fb5a00fb0ee1f4386f3dd17834aebdf9e89c21fcd3307109709"

[[files]]
file = "config/jade/jade.json"
hash = "8a57b8690ae69bac1e3c575a1a841a0c017f5ab3baadb6ba78f71a4bf0541ce0"

[[files]]
file = "config/jade/plugins.json"
hash = "8daf20878a02aab8611856f409ea0b33f721ef1d5be4bad4053d446e9634ba28"

[[files]]
file = "config/jade/sort-order.json"
hash = "d3f3be9b97417e8f177e1500b1d1f606562749b2eca47387eff162dc1b924e24"

[[files]]
file = "config/jade/usernamecache.json"
hash = "b22ed10ad081a907fe3e34e91cd8664ae80391ec8053fb9bede77fd2c44d7dd9"

[[files]]
file = "config/roughlyenoughitems/config.json5"
hash = "e20428580f54cb128b11bb54b38b4c9957473f5494628bcf42c7c358276f9759"

[[files]]
file = "config/rrls.toml"
hash = "675224bb453de73283e2e25fca52e47ce6ea1d2e9c6c2834eff51bf43d7c2a4f"

[[files]]
file = "config/shouldersurfing-client.toml"
hash = "880d1725e8bc4b9a4fb2753a5d698fa380d822afb007cd92d618e7254ea3ff33"

[[files]]
file = "config/skinshuffle/config.json"
hash = "662c8542ea661fc5321a22e99df6dafd0d6055ed0416a3fc767df130a9953a52"

[[files]]
file = "icon.png"
hash = "c36c0efbe5be0b9cf0fdfe54dbe17bea53295ac2a372d1203aa0f5c9c68d2bc7"

[[files]]
file = "journeymap/config/6.0/journeymap.core.config"
hash = "f186361722ed93165d61b42169ee0495310f7032b32a77f0f09c34f1c8dff6e3"

[[files]]
file = "journeymap/config/6.0/journeymap.fullmap.config"
hash = "b767cc9b4c8f8aadd2f07e03af345b51a44077d5a5c9d6ff491d57f0bb5d2e32"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap.config"
hash = "8cda76eb64346eb0b4c4fd567aa32b8a2c752a6600170db33729568ef0f7ad70"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap2.config"
hash = "26fd46b816044dbbc8fbd5fca1514b77598db69d3c239195edf0d7a40f969685"

[[files]]
file = "journeymap/config/6.0/journeymap.rendering.config"
hash = "adb365c27dcbf3a24b697cdb63f96bc6b09a179a2bea94397d146bdb890ac967"

[[files]]
file = "journeymap/config/6.0/journeymap.topo.config"
hash = "429c48cf38f5acb051b98ac7577e95fcf48b297d01cd83fd36e07c24c8416cad"

[[files]]
file = "journeymap/config/6.0/journeymap.waypoint.config"
hash = "a6e25c86ca2b8aa32a85829d7c39a31ccae7d749b240a55ea2000cb8cbcc490c"

[[files]]
file = "journeymap/config/6.0/journeymap.webmap.config"
hash = "6f472441a8c7377731ff5f9ad43f46951595c8a4969d1ba4b1055aa185a38c23"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "f53a77d8e152c94ab65a613dc222b13585b173a38141d74076a3e3ffc0575519"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "9ce55dc09b4b2a28b39ae47d146cfe5399dfc74666d9ae53811bdef4058b3491"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "39792a11da59cebc770f3918dd0ad53637bcbd206dc19bfa6709392bfd2d1830"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "424b579f2216c3ae3b2f64020635230e5493cdd8950635c9ba905c0487f6ecee"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "004aa46b68560131a4644928de6f312ef9c7ae73a180cfb53aa0f971a6d15172"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "f793ba4347e69a3fdcb1f6c0f84f4f27e7e16d3c7e1f8023db9debb81f53183b"
metafile = true

[[files]]
file = "mods/better-selection.pw.toml"
hash = "5f13e2470d769f613652ff4378a31c86b5915fe67032c94c1be5aeed06610b4d"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "5fe7e26e9534cf3d7829e8c4937c7b700d2084b6345aed901c1c3de9a80f49fa"
metafile = true

[[files]]
file = "mods/betterstats.pw.toml"
hash = "7036fb63a898da2f8d63017223e9ac294e8189a0f9aed650b654a1f2a2e137a2"
metafile = true

[[files]]
file = "mods/bridging-mod.pw.toml"
hash = "7e9f534e3c25d1d757374b55f766ce7dc4c9a98bcae530b1571fc7f914ff86da"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "57ecfa2a5e81966ef7046d443b076e2b94c85b9f0ad8d6cb126106e3d5967dd3"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "9e21cc4fae5ed88e306b4601c5e1533f883aa8b60c6e36dedeec82718be87059"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "b50378ddd8de5877ce51ded7616ebbf3ad0a5e18af8125a473411fbabc6c37cd"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "7112f698dda447ec4f1c6474683308487d51e93ec8dbe26c7f81d0fdd4c9fdb0"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "23bdbf17e1fd8aeed7efeeea72741662734199dbef0b2adfac2ba795acf5ca40"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "5a6ede5d2b8ea2a2d05e75243a0f294cdec35cc9684400d1b45d9b142e33cd4a"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "30ac8878dbdb811eb5f7dfc727cfa1c0f272f29efbce57ea05457921a271dd05"
metafile = true

[[files]]
file = "mods/detail-armor-bar-reconstructed.pw.toml"
hash = "e63a932c65fdc3a3ebad46cccf8dfda8761e346b6ab3dc30f25a6aec2b48a4da"
metafile = true

[[files]]
file = "mods/dynamic-crosshair.pw.toml"
hash = "4ac2843a21303aefa4638806c0278e8ef8fbf8cf1475320f4a2c02f88dd235ad"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "c76a6e9192ddb2a582e78d15b589188022a8fa3db09bf061d33d5f64baae81c8"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "3303ffc99bfefa5591660f2654766dac92666590c27a192cc88a5808cd120763"
metafile = true

[[files]]
file = "mods/eating-animation-fabric.pw.toml"
hash = "ca66d992b56e2993288195caadd2a9ce2eb2dd0bfceeb396747da712bdb933bd"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "9e37d8953c537212de3dc59aec2e081979b39671ab537474f71d53666aff81b2"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "f13154c42b7c33d21560292453a5d30d701ae5c73d271b0af842d4c8cfe0b113"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "949b56f74870f3722aa82cbc0af1f34b715d62007587c3ff65c47bafb15a58bc"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "212a90f8ab7004e831d3a956c27f8fd522b894569e7e4d36268d894f00cf5583"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "0e28ba15ba1769864a4af0b2f7ffaa3c90017b49633bef2a843b14a46e9a791d"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "94f000249d21c4fc3b7744f9579bb6ac0d48e6bf4860fad16f23c997950a47f3"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "be4e721e1d51831ecbc54600248be8b15ab73599d8d23cc48c95f3abdb092e0b"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "1bcebf42f650151bf068b968e2b27b05c4b278bb9a31f2c0b64c4a462d3ff787"
metafile = true

[[files]]
file = "mods/first-person-model.pw.toml"
hash = "ef9f88669bc72b1e89798877f7dd8a3466738da8e96acf3a81de0f779b0be03f"
metafile = true

[[files]]
file = "mods/forge-config-api-port-fabric.pw.toml"
hash = "d0e586bf4b4f9f003b1de1a3e18f67540233a0295b487009047056198f694f0f"
metafile = true

[[files]]
file = "mods/free-inventory.pw.toml"
hash = "d6588fade687ae5254313807598cd7732f1917e71dc202e387d11a077ab09d6c"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "736c8917697c7640f3aceddc8e9ce2eac770048c3e3163aa16a7872d5bb04c45"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "5d295245d23f4de878426a2edd1a6d1499a71b6acd9848c8631ad46504b3689b"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "40fa748597b1da468d9d0ef756ab55bb591e214695b93ef66feafd7cd6520a33"
metafile = true

[[files]]
file = "mods/invmovecompats.pw.toml"
hash = "c5732bb80de9248a43375a6a9d22d71066b4e5ec06d2829c1dbb80d4a84eec47"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "b31e45972ba08291e168f9d93ed14d679a8799983b7bce7ca38faa795a85bf3a"
metafile = true

[[files]]
file = "mods/itemphysic.pw.toml"
hash = "e74508278270d344120b5f82be0bc9f6c51747d7f94420d823192e287b04ad4d"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "c7d2fb2997874b6ef69179a1bc3181e7e4431932903dc6a776784fadc10afa1c"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "252b6581ba3fa2cce52a4bdf114020a2e7e069a42b35b6187ac3e21141b3a00a"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "f86e4b3d76b9b6bfd7318c0aefbbc269d3973263b2e9e247b5c2c997ec255d24"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "94944bc843327b8c13b34ee3ea4c16671d3102d5ae6845a48e5c86592d9696bb"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "a3e8ab5b65ff403b1e578f50465a67743ff2d6943bd47458be482e44f5642754"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "c2fe9a1900ceb3a6014ccb83344aa4ab5ddf65c8bf660044469c3c90c7ed9010"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "0a294ec59f287931a4748716730aa3a5509a778bb5c39eab881f21bdfef273e5"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "3cd8155341a4233955ff9892a3b7b5da6dc6d8d892863b2f544328f2731f7f03"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "0c3e67242799f8dca62ba5bba5556d72d13d6247c4092eab28a0a0be5b93fdff"
metafile = true

[[files]]
file = "mods/no-more-popups.pw.toml"
hash = "53633508694b314c003866564cc4b8099982ec840d18d21b761459513a253f8c"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "ae0783f3455e72023fac34f0ebe965ad1b3dbd813f155e2f7fb97e2da029e103"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "ad9e8ce3e41f717fd4a0b748bc51a9ccac72eca81d64c96a63278560c2db890f"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "e3c482b20c0bb250716495a2c05efae13b520849de1cfb27ea2ad704fb325873"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "2494505990ebe04a740fbae936efdf4d24a52071c04d3b73d215b9539e59817b"
metafile = true

[[files]]
file = "mods/roughly-enough-items.pw.toml"
hash = "a01882a8a94bcf77e68f3d03d8a1d3098de9b63ee455d7ee0ee300bc8974b2c7"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "6dff4b6eccb5ecca2c5b15bf8e24523298819839db487f02a65636c2fbe3fdd1"
metafile = true

[[files]]
file = "mods/seamless.pw.toml"
hash = "529cb4f12209cedb7b15acc1cf8639e845cf1ef2a9dd7a23652ca517e7db3862"
metafile = true

[[files]]
file = "mods/shoulder-surfing-reloaded.pw.toml"
hash = "803ebab3c151fd5d81ea836f67f8f63116209ee07df52acc19fc6658ddb41dfa"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "e4b0fcff8630f9c3919d1ffa6e519c4fb9e8d814d6c321ad2374877863e84b51"
metafile = true

[[files]]
file = "mods/skin-layers-3d.pw.toml"
hash = "bd4cfd8701633c013cacde0c311a24261020abdce657e3760166d6af8660f745"
metafile = true

[[files]]
file = "mods/skinshuffle.pw.toml"
hash = "e6950ce48f8679380c1ebe82c5887fb5835e5d9b613ad5d247d0cd2306f8bd68"
metafile = true

[[files]]
file = "mods/smooth-scroll.pw.toml"
hash = "69d9366753ade6e5dbcbbac31372fae83d6b37b81a63a797a217aa69e97f2992"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "898e14275dd5cc187dee2b8f8fc83b4f0cdb56430b7fa64a8055e006d0249ce7"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "d784b4d9ee7f99008808bd6407cb3f402e46712c90f978b4ccfcd5e81eb7f794"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "f73a48751e13380b87296e5b9627c9f6669efda386bd646fd5c499b344570f46"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "dc64fa7d848e9dbb47917b2512896e28f4b23a0d9a3585aab37fcc5393a272ee"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "503a13fb7a8188f8434a82df32c16644cba3d0f25e31da88626acc52af03da41"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "fabf45760d3b99280fc669e4d545c51339d65dee508fea3ce8858841d77c5bdd"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
hash = "605e24df28c2facc0e22397656ff507548b86badc0a8fbc278c72f6ccd3da242"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "5d6abaadd99d9e779849c989017e752b93b5ad023d0a51ff84628c4bc22377fb"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f8b22a3818eb55e9b7eafa4cc6b1b44482b88524d4134d544dfb795d9aea058d"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "1836c4b896229b4283d28009951c913b518df7aefd0ccb05f12cd954c3a7deb8"
metafile = true

[[files]]
file = "options.txt"
hash = "bc307212710702f562d4887c8f921e3c3917045041c6cc9383b540355ebc55c3"

[[files]]
file = "resourcepacks/better-ipn-buttons.pw.toml"
hash = "344cfb1bf3259c3534dc0b0737aef164f0f3c97ddf75f15fd564fbd93c427c0d"
metafile = true

[[files]]
file = "resourcepacks/connected-paths.pw.toml"
hash = "dc065d9bb3aaad0eefdf5158211929943835493c709e2fb7ed29a6d246ea9c06"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "2d8aab62e51d84e33920e15cdd34fd164d971b01aede0c3d17abcd08117d33a9"
metafile = true

[[files]]
file = "resourcepacks/fast-better-grass.pw.toml"
hash = "5310da73a0fb83b049f5e5a3fdd82c73873da024d0ce663a2365c209c002fd0a"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "15f5872ee75d21be2e6cbd25669e423a2a764312562e5cdfdc4e34af160dc6d3"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "c78e5aadda0f2be8481cefeaa7fc27fce87c34097dbfd29aa715fef2b1f55ba4"
metafile = true

[[files]]
file = "resourcepacks/minecraft-3d-default.pw.toml"
hash = "03d6565210f9674a4eb2da0cef0db986571cea9444d7e80b67775c699253db87"
metafile = true

[[files]]
file = "resourcepacks/recolourful-containers-gui-hud-dark.pw.toml"
hash = "91d9ebebc72f713caf3c181839d2966190e3018fdcf87fd02ffa94e1244cf6df"
metafile = true

[[files]]
file = "resourcepacks/torches-reimagined.pw.toml"
hash = "24ac06885ef01025f8abe7d57ae0452bb18ca9eba084092ce2fc444f6272da58"
metafile = true

[[files]]
file = "resourcepacks/translations-for-sodium.pw.toml"
hash = "7fb83199c50d224fcf15e229e9168bd5412ca353927452e2a52bc08eb5443a24"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "006170836f3180d229a6b95e1b33c060d7afcd0755273669faf78e86f50579ed"
metafile = true
