hash-format = "sha256"

[[files]]
file = "config/betterf3.json"
hash = "0028abb010568e5d31c2d12390a18a471a495591a24bf408abea3c151e8d234e"

[[files]]
file = "config/detailarmorbar.json"
hash = "a5c688952ee55d6ac48c632baa5667d8adc20758ab2fd6c913c1b411bb4cad71"

[[files]]
file = "config/euphoria_patcher.properties"
hash = "66793f6eb032dba20841b7b015cf96550baec9686ee9cf758edc2e41b193ec25"

[[files]]
file = "config/inventoryprofilesnext/inventoryprofiles.json"
hash = "3b2f0b16fe70aa6a7720622bf7dcb99e59e412c37169763b3af0c8b310b74d5e"

[[files]]
file = "config/iris.properties"
hash = "4eb525ec220ff749911e5d1f8f6eab09ec9d78875dd4baf6d63e6a50ba069ac0"

[[files]]
file = "config/jade/jade.json"
hash = "93e098f8882bbfe9eaba05694016fff55a911114d1cea2a046915e6f4253d64b"

[[files]]
file = "config/jade/plugins.json"
hash = "8daf20878a02aab8611856f409ea0b33f721ef1d5be4bad4053d446e9634ba28"

[[files]]
file = "config/no-more-popups.json"
hash = "31e5140ee7bb35c73c8ae74eb785eca3c81caf235d467fd4a38e75e86e0a6aa7"

[[files]]
file = "config/roughlyenoughitems/config.json5"
hash = "e20428580f54cb128b11bb54b38b4c9957473f5494628bcf42c7c358276f9759"

[[files]]
file = "config/rrls.toml"
hash = "675224bb453de73283e2e25fca52e47ce6ea1d2e9c6c2834eff51bf43d7c2a4f"

[[files]]
file = "config/shouldersurfing-client.toml"
hash = "880d1725e8bc4b9a4fb2753a5d698fa380d822afb007cd92d618e7254ea3ff33"

[[files]]
file = "config/skinshuffle/config.json"
hash = "662c8542ea661fc5321a22e99df6dafd0d6055ed0416a3fc767df130a9953a52"

[[files]]
file = "config/voicechat/voicechat-client.properties"
hash = "565252c49707cbd0503824432c6cde64739eaa56130c1d3b8096c6754ca25853"

[[files]]
file = "icon.png"
hash = "c36c0efbe5be0b9cf0fdfe54dbe17bea53295ac2a372d1203aa0f5c9c68d2bc7"

[[files]]
file = "journeymap/config/6.0/journeymap.core.config"
hash = "f186361722ed93165d61b42169ee0495310f7032b32a77f0f09c34f1c8dff6e3"

[[files]]
file = "journeymap/config/6.0/journeymap.fullmap.config"
hash = "b767cc9b4c8f8aadd2f07e03af345b51a44077d5a5c9d6ff491d57f0bb5d2e32"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap.config"
hash = "8cda76eb64346eb0b4c4fd567aa32b8a2c752a6600170db33729568ef0f7ad70"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap2.config"
hash = "26fd46b816044dbbc8fbd5fca1514b77598db69d3c239195edf0d7a40f969685"

[[files]]
file = "journeymap/config/6.0/journeymap.rendering.config"
hash = "adb365c27dcbf3a24b697cdb63f96bc6b09a179a2bea94397d146bdb890ac967"

[[files]]
file = "journeymap/config/6.0/journeymap.topo.config"
hash = "429c48cf38f5acb051b98ac7577e95fcf48b297d01cd83fd36e07c24c8416cad"

[[files]]
file = "journeymap/config/6.0/journeymap.waypoint.config"
hash = "a6e25c86ca2b8aa32a85829d7c39a31ccae7d749b240a55ea2000cb8cbcc490c"

[[files]]
file = "journeymap/config/6.0/journeymap.webmap.config"
hash = "6f472441a8c7377731ff5f9ad43f46951595c8a4969d1ba4b1055aa185a38c23"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "f53a77d8e152c94ab65a613dc222b13585b173a38141d74076a3e3ffc0575519"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "cdc6274305b261087764409f7a7e747e4421afe2fe391b07916ed5fccfca4062"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "9ce55dc09b4b2a28b39ae47d146cfe5399dfc74666d9ae53811bdef4058b3491"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "39792a11da59cebc770f3918dd0ad53637bcbd206dc19bfa6709392bfd2d1830"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "424b579f2216c3ae3b2f64020635230e5493cdd8950635c9ba905c0487f6ecee"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "e2f2a6f6ff38054ce8d91a43a20b79ea7b4e84cb924142fb7d2bcfdd95fe5b57"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "f793ba4347e69a3fdcb1f6c0f84f4f27e7e16d3c7e1f8023db9debb81f53183b"
metafile = true

[[files]]
file = "mods/better-selection.pw.toml"
hash = "5f13e2470d769f613652ff4378a31c86b5915fe67032c94c1be5aeed06610b4d"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "5fe7e26e9534cf3d7829e8c4937c7b700d2084b6345aed901c1c3de9a80f49fa"
metafile = true

[[files]]
file = "mods/betterstats.pw.toml"
hash = "7036fb63a898da2f8d63017223e9ac294e8189a0f9aed650b654a1f2a2e137a2"
metafile = true

[[files]]
file = "mods/bridging-mod.pw.toml"
hash = "7e9f534e3c25d1d757374b55f766ce7dc4c9a98bcae530b1571fc7f914ff86da"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "57ecfa2a5e81966ef7046d443b076e2b94c85b9f0ad8d6cb126106e3d5967dd3"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "9e21cc4fae5ed88e306b4601c5e1533f883aa8b60c6e36dedeec82718be87059"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "b50378ddd8de5877ce51ded7616ebbf3ad0a5e18af8125a473411fbabc6c37cd"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "7112f698dda447ec4f1c6474683308487d51e93ec8dbe26c7f81d0fdd4c9fdb0"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "23bdbf17e1fd8aeed7efeeea72741662734199dbef0b2adfac2ba795acf5ca40"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "5a6ede5d2b8ea2a2d05e75243a0f294cdec35cc9684400d1b45d9b142e33cd4a"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "30ac8878dbdb811eb5f7dfc727cfa1c0f272f29efbce57ea05457921a271dd05"
metafile = true

[[files]]
file = "mods/detail-armor-bar-reconstructed.pw.toml"
hash = "e63a932c65fdc3a3ebad46cccf8dfda8761e346b6ab3dc30f25a6aec2b48a4da"
metafile = true

[[files]]
file = "mods/dynamic-crosshair.pw.toml"
hash = "a714422ad4d06d2576cf24770aefdf0fa7bf5add3cc9c445023ac0de1d76003c"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "02a69054bfdf68319fac665feab07b0b2e0469685c86488ed189301f26df6b74"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "2864c89aa5d04d6f319bce5f6a0cbfc731512956c9acd59fafd3e1e5a1e9e7b6"
metafile = true

[[files]]
file = "mods/eating-animation-fabric.pw.toml"
hash = "ca66d992b56e2993288195caadd2a9ce2eb2dd0bfceeb396747da712bdb933bd"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "f4fb9245abbdb8c359a4b4898e9c8f03e2908d32335e4e6e9650d001f669f9aa"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "c87624b6bb030922148c12c8aad7e3e415ca3f26d1f4355806a31b77aa3b1c42"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "068520363709db9632207ee223dcdc9dc3a33b295806b07b0f4e6b0556b9009a"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "212a90f8ab7004e831d3a956c27f8fd522b894569e7e4d36268d894f00cf5583"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "0e28ba15ba1769864a4af0b2f7ffaa3c90017b49633bef2a843b14a46e9a791d"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "1aa94f817646eea69478dc3dce662c3f4b674359d7ce34cf58fd38dcbc56e458"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "be4e721e1d51831ecbc54600248be8b15ab73599d8d23cc48c95f3abdb092e0b"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "9a53d0956a5f25c6c5de1d34a6497c2d323486bf340935db6b364815aae596be"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "1bcebf42f650151bf068b968e2b27b05c4b278bb9a31f2c0b64c4a462d3ff787"
metafile = true

[[files]]
file = "mods/first-person-model.pw.toml"
hash = "ef9f88669bc72b1e89798877f7dd8a3466738da8e96acf3a81de0f779b0be03f"
metafile = true

[[files]]
file = "mods/forge-config-api-port-fabric.pw.toml"
hash = "d0e586bf4b4f9f003b1de1a3e18f67540233a0295b487009047056198f694f0f"
metafile = true

[[files]]
file = "mods/free-inventory.pw.toml"
hash = "a1396d8ed31795e01d54e16b25aa4b61ffbc2d4790b087faaaf2c1282dc1be6a"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "9e2e75d2cf89eb66aaa1f9423cec14e8b496a8aa0cfa9142edc4441369ed977e"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "5aff706b484a368a4679b23cb2502154968b89251f17e0d4740ac189218c3dc7"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "40fa748597b1da468d9d0ef756ab55bb591e214695b93ef66feafd7cd6520a33"
metafile = true

[[files]]
file = "mods/invmovecompats.pw.toml"
hash = "c5732bb80de9248a43375a6a9d22d71066b4e5ec06d2829c1dbb80d4a84eec47"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "b31e45972ba08291e168f9d93ed14d679a8799983b7bce7ca38faa795a85bf3a"
metafile = true

[[files]]
file = "mods/itemphysic.pw.toml"
hash = "e74508278270d344120b5f82be0bc9f6c51747d7f94420d823192e287b04ad4d"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "c7d2fb2997874b6ef69179a1bc3181e7e4431932903dc6a776784fadc10afa1c"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "252b6581ba3fa2cce52a4bdf114020a2e7e069a42b35b6187ac3e21141b3a00a"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "7438e773f85e37b376469cbe8749525e3353ff38711ddb3911dde77bbd0e3388"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "94944bc843327b8c13b34ee3ea4c16671d3102d5ae6845a48e5c86592d9696bb"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "2edafdc423051b21edbe49f433e73e6ba3164dfb079673355003e0f889e7ddf3"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "c2fe9a1900ceb3a6014ccb83344aa4ab5ddf65c8bf660044469c3c90c7ed9010"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "0a294ec59f287931a4748716730aa3a5509a778bb5c39eab881f21bdfef273e5"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "3cd8155341a4233955ff9892a3b7b5da6dc6d8d892863b2f544328f2731f7f03"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "0c3e67242799f8dca62ba5bba5556d72d13d6247c4092eab28a0a0be5b93fdff"
metafile = true

[[files]]
file = "mods/no-more-popups.pw.toml"
hash = "7a5d6a474afc81f35c56431a5a123ac567b85b2e01dbd928bee55816b94bb55f"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "ae0783f3455e72023fac34f0ebe965ad1b3dbd813f155e2f7fb97e2da029e103"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "ad9e8ce3e41f717fd4a0b748bc51a9ccac72eca81d64c96a63278560c2db890f"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "e3c482b20c0bb250716495a2c05efae13b520849de1cfb27ea2ad704fb325873"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "2494505990ebe04a740fbae936efdf4d24a52071c04d3b73d215b9539e59817b"
metafile = true

[[files]]
file = "mods/roughly-enough-items.pw.toml"
hash = "a01882a8a94bcf77e68f3d03d8a1d3098de9b63ee455d7ee0ee300bc8974b2c7"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "6dff4b6eccb5ecca2c5b15bf8e24523298819839db487f02a65636c2fbe3fdd1"
metafile = true

[[files]]
file = "mods/seamless.pw.toml"
hash = "529cb4f12209cedb7b15acc1cf8639e845cf1ef2a9dd7a23652ca517e7db3862"
metafile = true

[[files]]
file = "mods/shoulder-surfing-reloaded.pw.toml"
hash = "111b5f398a8d9e8b3eac6163b0a4bfb8f1048563e3ea7756c0fff0095b416789"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "05ac71bf8e11d27c8482d7b6ffec7eb6ce087fc7a22a055f04fe61a905ef3c34"
metafile = true

[[files]]
file = "mods/skin-layers-3d.pw.toml"
hash = "bd4cfd8701633c013cacde0c311a24261020abdce657e3760166d6af8660f745"
metafile = true

[[files]]
file = "mods/skinshuffle.pw.toml"
hash = "e6950ce48f8679380c1ebe82c5887fb5835e5d9b613ad5d247d0cd2306f8bd68"
metafile = true

[[files]]
file = "mods/smooth-scroll.pw.toml"
hash = "69d9366753ade6e5dbcbbac31372fae83d6b37b81a63a797a217aa69e97f2992"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "898e14275dd5cc187dee2b8f8fc83b4f0cdb56430b7fa64a8055e006d0249ce7"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "d784b4d9ee7f99008808bd6407cb3f402e46712c90f978b4ccfcd5e81eb7f794"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "f73a48751e13380b87296e5b9627c9f6669efda386bd646fd5c499b344570f46"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "dc64fa7d848e9dbb47917b2512896e28f4b23a0d9a3585aab37fcc5393a272ee"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "503a13fb7a8188f8434a82df32c16644cba3d0f25e31da88626acc52af03da41"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "fabf45760d3b99280fc669e4d545c51339d65dee508fea3ce8858841d77c5bdd"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
hash = "605e24df28c2facc0e22397656ff507548b86badc0a8fbc278c72f6ccd3da242"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "5d6abaadd99d9e779849c989017e752b93b5ad023d0a51ff84628c4bc22377fb"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f8b22a3818eb55e9b7eafa4cc6b1b44482b88524d4134d544dfb795d9aea058d"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "1836c4b896229b4283d28009951c913b518df7aefd0ccb05f12cd954c3a7deb8"
metafile = true

[[files]]
file = "options.txt"
hash = "ebd49372bf41fb8c30574c3bcf4c41b9032d5f42a8b7ef93548faa632628fc2f"

[[files]]
file = "resourcepacks/better-ipn-buttons.pw.toml"
hash = "344cfb1bf3259c3534dc0b0737aef164f0f3c97ddf75f15fd564fbd93c427c0d"
metafile = true

[[files]]
file = "resourcepacks/connected-bricks.pw.toml"
hash = "b1f6d18e011da27a5441fb7d1749e6df70f7965aa23a318f1143f8cc1745ad0f"
metafile = true

[[files]]
file = "resourcepacks/connected-paths.pw.toml"
hash = "a48c0063313ca6bb027668a668f95f7460a37929656f4fc5b6ad7cf5c228d187"
metafile = true

[[files]]
file = "resourcepacks/connected-rocks.pw.toml"
hash = "86c9ec0b0d0d1cc3226f40116e25bb573e987d905bde72c81644e19ef9d4dc51"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "2d8aab62e51d84e33920e15cdd34fd164d971b01aede0c3d17abcd08117d33a9"
metafile = true

[[files]]
file = "resourcepacks/fast-better-grass.pw.toml"
hash = "5310da73a0fb83b049f5e5a3fdd82c73873da024d0ce663a2365c209c002fd0a"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "72b919a0242253a1540a0fa424ea5a652787365186ac9f5fa5a67583bb5d368c"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "c78e5aadda0f2be8481cefeaa7fc27fce87c34097dbfd29aa715fef2b1f55ba4"
metafile = true

[[files]]
file = "resourcepacks/minecraft-3d-default.pw.toml"
hash = "03d6565210f9674a4eb2da0cef0db986571cea9444d7e80b67775c699253db87"
metafile = true

[[files]]
file = "resourcepacks/recolourful-containers-gui-hud-dark.pw.toml"
hash = "91d9ebebc72f713caf3c181839d2966190e3018fdcf87fd02ffa94e1244cf6df"
metafile = true

[[files]]
file = "resourcepacks/torches-reimagined.pw.toml"
hash = "24ac06885ef01025f8abe7d57ae0452bb18ca9eba084092ce2fc444f6272da58"
metafile = true

[[files]]
file = "resourcepacks/translations-for-sodium.pw.toml"
hash = "701813f85a323e9d5609dc31c911f5872dfb8a69a8ff753c113046e927cd5d1e"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "006170836f3180d229a6b95e1b33c060d7afcd0755273669faf78e86f50579ed"
metafile = true
