name = "Net Play MC"
author = "Alfakynz"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9dcfa23ab522ab13c92011cf24cadc140229b0251548ef34765c3cfa810eb15"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
