name = "Net Play MC"
author = "Alfakynz"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eac5fc50bd3b4a9cf81344760f1ef1fcd74c02c651d02c43c10635f297a1be2b"

[versions]
fabric = "0.18.2"
minecraft = "1.21.6"
