hash-format = "sha256"

[[files]]
file = "configureddefaults/config/betterf3.json"
hash = "0028abb010568e5d31c2d12390a18a471a495591a24bf408abea3c151e8d234e"

[[files]]
file = "configureddefaults/config/euphoria_patcher.properties"
hash = "66793f6eb032dba20841b7b015cf96550baec9686ee9cf758edc2e41b193ec25"

[[files]]
file = "configureddefaults/config/inventoryprofilesnext/integrationHints/exampleIntegrationHints.json"
hash = "ca413dea02cce69c69dccdc525fb0ec013236876eff2d142772c68db3d772d3a"

[[files]]
file = "configureddefaults/config/inventoryprofilesnext/inventoryprofiles.json"
hash = "cc6948c287851fdb08146d86250841e4d6ee9c802ebba1f8df13aa3445528be0"

[[files]]
file = "configureddefaults/config/jade/hide-blocks.json"
hash = "309df4ae96864c19eae41b646d58497c85a73b1fc3c584e772ef4d5822794baa"

[[files]]
file = "configureddefaults/config/jade/hide-entities.json"
hash = "3741bb54a4535fb5a00fb0ee1f4386f3dd17834aebdf9e89c21fcd3307109709"

[[files]]
file = "configureddefaults/config/jade/jade.json"
hash = "8a57b8690ae69bac1e3c575a1a841a0c017f5ab3baadb6ba78f71a4bf0541ce0"

[[files]]
file = "configureddefaults/config/jade/plugins.json"
hash = "d01aec2b1f436d3cc03dc0be05817918cf60e8781fc24adc774f530ad24580ad"

[[files]]
file = "configureddefaults/config/jade/sort-order.json"
hash = "d3f3be9b97417e8f177e1500b1d1f606562749b2eca47387eff162dc1b924e24"

[[files]]
file = "configureddefaults/config/jade/usernamecache.json"
hash = "b22ed10ad081a907fe3e34e91cd8664ae80391ec8053fb9bede77fd2c44d7dd9"

[[files]]
file = "configureddefaults/config/rrls.toml"
hash = "e640a0284af42c946e5495440466beae329f32f9b7aa068a9d1d51559b9624f8"

[[files]]
file = "configureddefaults/config/shouldersurfing-client.toml"
hash = "880d1725e8bc4b9a4fb2753a5d698fa380d822afb007cd92d618e7254ea3ff33"

[[files]]
file = "configureddefaults/journeymap/config/6.0/journeymap.core.config"
hash = "f186361722ed93165d61b42169ee0495310f7032b32a77f0f09c34f1c8dff6e3"

[[files]]
file = "configureddefaults/journeymap/config/6.0/journeymap.fullmap.config"
hash = "b767cc9b4c8f8aadd2f07e03af345b51a44077d5a5c9d6ff491d57f0bb5d2e32"

[[files]]
file = "configureddefaults/journeymap/config/6.0/journeymap.minimap.config"
hash = "8cda76eb64346eb0b4c4fd567aa32b8a2c752a6600170db33729568ef0f7ad70"

[[files]]
file = "configureddefaults/journeymap/config/6.0/journeymap.minimap2.config"
hash = "26fd46b816044dbbc8fbd5fca1514b77598db69d3c239195edf0d7a40f969685"

[[files]]
file = "configureddefaults/journeymap/config/6.0/journeymap.rendering.config"
hash = "adb365c27dcbf3a24b697cdb63f96bc6b09a179a2bea94397d146bdb890ac967"

[[files]]
file = "configureddefaults/journeymap/config/6.0/journeymap.topo.config"
hash = "429c48cf38f5acb051b98ac7577e95fcf48b297d01cd83fd36e07c24c8416cad"

[[files]]
file = "configureddefaults/journeymap/config/6.0/journeymap.waypoint.config"
hash = "a6e25c86ca2b8aa32a85829d7c39a31ccae7d749b240a55ea2000cb8cbcc490c"

[[files]]
file = "configureddefaults/journeymap/config/6.0/journeymap.webmap.config"
hash = "6f472441a8c7377731ff5f9ad43f46951595c8a4969d1ba4b1055aa185a38c23"

[[files]]
file = "configureddefaults/options.txt"
hash = "4c934db603d72784702803e42d0af29f00e688b4eb85fc706b5006822cc1d886"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "5c1b3be910212e79c31acc44a24c58f32ad2f3e7e5c6cfd5456ffb41fa4001ee"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "6ae25ae9d92019f75b0ef1bb554e5ff634c499b3cc32fc7b6181cee8b6535144"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "6239435a6e7bd363eecb8a0a6c16476056e09b0a4d175391ca1dd4521e28a21f"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "ca86c0a6572b7e37bad85e9484095c75096fa064d28fe03fa6f0e1e9a55b8f15"
metafile = true

[[files]]
file = "mods/better-selection.pw.toml"
hash = "5f13e2470d769f613652ff4378a31c86b5915fe67032c94c1be5aeed06610b4d"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "327de73ab5fdcc5f8d80485f2b25704a576e03df4f22007b847fc055c7f26eee"
metafile = true

[[files]]
file = "mods/betterstats.pw.toml"
hash = "597d6f3fa908ea0e43592255b43b3c8755e710a38eae3a75aeb3c5395243a69d"
metafile = true

[[files]]
file = "mods/bridging-mod.pw.toml"
hash = "6dda40a07460cc1bd4659c1340b15e1c8cc59d63da39795dd877d2d58dcc55b6"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "03a5647048657399fc168ca206a1e2c5c2a299432ef6d8ec8b840d54407591df"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "287209b1b1b7c27f11f59ef3eda5fb5f4431aa6b51701870a426c0b39da74fce"
metafile = true

[[files]]
file = "mods/configured-defaults.pw.toml"
hash = "07c016ed70aa998609dc5ac1bae1ea53f03d20aea9eec9655c8b64c457f7f7a7"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "1165355580ac183fb3c6ac0b34f8600a34312d2e64118c83602b7b85b95f93ba"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a826fbce1a20169613e387719b40a05e95a0ca8ede805b82fa686533a0550713"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "46926bb6cadb618ae673ac978307743ac334a8d9f21d88ea731cb6829cd7167a"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "38b8a8963b4d330ad739002d4dea78312ff2dffecf8ca39e8c692e7ee228d46e"
metafile = true

[[files]]
file = "mods/dynamic-crosshair.pw.toml"
hash = "0d6457e70240c370d34950f45c9bee62b77248a9f8f5d7b9dfc562184b3e00d6"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "532f682da1652b2918b742b01fab0ee5980b87f181c641dcccfecc0ba044ecc7"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "26848d509acd34d269294947c037311b34639e993a820780930a31962d4a7239"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "0675e02b9d397fd75e554877c9a97015d52fbd9748e7ee5220da4095b50889cd"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "bec0eaf7f1b7d966344482d14184a2b3afbed5309b8d819f9fc84ff661894e2b"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "212a90f8ab7004e831d3a956c27f8fd522b894569e7e4d36268d894f00cf5583"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "89fd86742345d5731eb8cdb74094169d291b737e4f3847a2109f18672a484ab1"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "94f000249d21c4fc3b7744f9579bb6ac0d48e6bf4860fad16f23c997950a47f3"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "1c28d8fb640574e4d081340cc7e4dfd07ac08b3b21833467fc660b10e2a7af8c"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "3dcc43cbc807ec49377efe574b4670ee91e62474aee1bcd068495adea8bc1f6a"
metafile = true

[[files]]
file = "mods/first-person-model.pw.toml"
hash = "741bb2746ce52206ae6f8a7f7f826d89d7c1dbd1705d2faecbc5e66e2d1b72a8"
metafile = true

[[files]]
file = "mods/forge-config-api-port-fabric.pw.toml"
hash = "38a15008593221752c9e119b0eb1a26879002342892e1045cac707d2e9ca00b2"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "13b60b2a79f560b24444c898f3dd1329e98e908deb5e1ee2a22ca17ded7b1925"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "d72fc8c3cc940a15a2df81d0ed619e8ebeca966c5bd39921cea25797a0a88bb1"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "e5a41adb84a1daf65eb119a8c5aa65432c0be514c1f13635eda4d107732b1908"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "b15c3312a4cca50bf37dee2c669b8c52027b1264e4bd0800520471462596db24"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "805ddbc6d81dc4c48a102c4eaee06754e1520a857cea9617df4b5942b051a18d"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "23b7165d830ef3973324a7543df1189c26cde490f2d0907980d0441eaf0b7d31"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "c5775f6d97ebff11b128a909dd5a5dc15ccc896dc633a7499b73db90a78021f7"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "29d81a30d4acfc46fda4cfa4c40e57b49ce9823796b3b173daf059f679c2b675"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "a3e8ab5b65ff403b1e578f50465a67743ff2d6943bd47458be482e44f5642754"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "4f35bf07c47be05766892e81398645c30980dbf31206dbe668ad496e868e47c8"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "229d1eabf82bea64acb5421ff045294b895340fd4e44b80817b143a54d76126a"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "9a2cf1b5b5f996fdecc1c2b099fc715b20996bb0bd3b22b2af2588ec2abed567"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "63c5984aff4da464d4d4e02cac385f58f8eb9a7603cd688d61890a71c4ff636e"
metafile = true

[[files]]
file = "mods/no-more-popups.pw.toml"
hash = "53633508694b314c003866564cc4b8099982ec840d18d21b761459513a253f8c"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "46842d9d70da2e7b7531df5b95c3e95bb736899f70569b7bdfb8f47775d22ddb"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "ce1fd5b331e0811bd4d097c3c3737d9896eb1102a9c9c6df49cc00dd43362c59"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "b907e3a9a53b99c2643e5a403e1cc5e63893e4e92da858f674e6cf0023cfe406"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "2494505990ebe04a740fbae936efdf4d24a52071c04d3b73d215b9539e59817b"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "80b76c60b4db627674a5ee72927323fd7cff9977ec36f553e52f859b7afce5c0"
metafile = true

[[files]]
file = "mods/shoulder-surfing-reloaded.pw.toml"
hash = "a15558e56980c6cfbf62342aec9e5d3b1ba27c5061de4e0806e5b4cacdd23fe3"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "dc054761f2d8307699afa47f5d4b0935c2deac2eb4aca2fd032dae512fa02f6f"
metafile = true

[[files]]
file = "mods/skin-layers-3d.pw.toml"
hash = "569088a9ed981a1a7f46a6c67aeb61c7236d6a61d7a14d9387526fa1c6bde228"
metafile = true

[[files]]
file = "mods/smooth-scroll.pw.toml"
hash = "9e4a8c99ac2558f37cbb0e8c4958668ed97761d39bd8f8490a10947dafc9ae56"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "4fae11d30258dea0f10529ab7a63b1df03b1f9a8d638781cddc29f2903b5daf8"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "cdf62992a654bf76495b999867271cd63f777e7af821ad2ca3f4099ccf58cd9d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "2bbbe84ce305111cb5cd483ddb75497da9fac5e29074ba527fcbb719c8f5e8f8"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "be9870bee0d6257fd87cf3a463e96bf9378110bc64a0e0194de1d836d31fd759"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "40154a78649133cc5eabd7be3642b6b591c5906c80305865192b50c7c8445419"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "bb38ead25815b48e90617bf993a9464591592a51031b30a41d848a4d216fa53b"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
hash = "c5a294ef234b8a198822c9ec440f518fc07b403d0b9d43322bb1374010392ee5"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "d8e3de0893d8f51f20589d62fced17eb56a5a70248cab6bfe68cd7a541ee4d8b"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "44884083814b7aac7697630e19a182f8b1a48c1479dc645b0876b6e62fc2cc0a"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "ff7ff3076468c77cf5c6c703bba376749e521c8c53266743599dbafdf37b5caa"
metafile = true

[[files]]
file = "resourcepacks/connected-paths.pw.toml"
hash = "f96b12a4b7a2e60865d524bb1ec052294d6d9aa59258c31d48816241bebe387a"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "2d8aab62e51d84e33920e15cdd34fd164d971b01aede0c3d17abcd08117d33a9"
metafile = true

[[files]]
file = "resourcepacks/fast-better-grass.pw.toml"
hash = "bb7d05bb7097173a4193e7a82b554d5748a849db9fd65c8515d7564f2988e656"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "15f5872ee75d21be2e6cbd25669e423a2a764312562e5cdfdc4e34af160dc6d3"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "92915b4b4a9fee4a48c9e3988541165838f385ae89f4305ba1668280b1176d31"
metafile = true

[[files]]
file = "resourcepacks/minecraft-3d-default.pw.toml"
hash = "4ae461fad9e6783151b8744f285e0bb553a94ebbdca6f32399ea56abbdd52703"
metafile = true

[[files]]
file = "resourcepacks/recolourful-containers-gui-hud-dark.pw.toml"
hash = "53cb7691a62166c5f65251f9eb24caafd7608c8fa60f111501a927f0097434bd"
metafile = true

[[files]]
file = "resourcepacks/torches-reimagined.pw.toml"
hash = "24ac06885ef01025f8abe7d57ae0452bb18ca9eba084092ce2fc444f6272da58"
metafile = true

[[files]]
file = "resourcepacks/translations-for-sodium.pw.toml"
hash = "ad42edaeac5410d8f4ef629805cc734ff3f80c45ddd27bcf1d64a38f34b80a4b"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "006170836f3180d229a6b95e1b33c060d7afcd0755273669faf78e86f50579ed"
metafile = true
