name = "Net Play MC"
author = "Alfakynz"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29c6405906a86c9f2e1167e60bff6e46bf6b6682c862786bab41fac342667aea"

[versions]
fabric = "0.18.2"
minecraft = "1.21.5"
