name = "Net Play MC"
author = "Alfakynz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a4694723fd9a7b0227b257e84d9ff88fdd6c4ea4c693b4330993fe5858387e1"

[versions]
fabric = "0.18.1"
minecraft = "1.21.5"
