name = "Net Play MC"
author = "Alfakynz"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e06ff313e6aa0874717fee60db8c52ad50742155878533693a01463c358e33b0"

[versions]
fabric = "0.18.4"
minecraft = "1.21.9"
