name = "Net Play MC"
author = "Alfakynz"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66b0a4d73b563faa318d732b37e05dc0adb4a93fc70cf3a8cda59f3fce7efd6d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.6"]
