name = "Net Play MC"
author = "Alfakynz"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a33c6600d6e99cd0448ef3521d8e69d697556937806865660c959f5b8624600f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.6"]
